//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: pb_15.proto
// Note: requires additional types generated from: pb_common.proto
namespace pb_15
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbGoodsList")]
  public partial class pbGoodsList : global::ProtoBuf.IExtensible
  {
    public pbGoodsList() {}
    
    private readonly global::System.Collections.Generic.List<pb_common.pbGoods> _goods_list = new global::System.Collections.Generic.List<pb_common.pbGoods>();
    [global::ProtoBuf.ProtoMember(1, Name=@"goods_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_common.pbGoods> goods_list
    {
      get { return _goods_list; }
    }
  
    private int? _update_timestamp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"update_timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int update_timestamp
    {
      get { return _update_timestamp?? default(int); }
      set { _update_timestamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool update_timestampSpecified
    {
      get { return this._update_timestamp != null; }
      set { if (value == (this._update_timestamp== null)) this._update_timestamp = value ? this.update_timestamp : (int?)null; }
    }
    private bool ShouldSerializeupdate_timestamp() { return update_timestampSpecified; }
    private void Resetupdate_timestamp() { update_timestampSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbEquipMove")]
  public partial class pbEquipMove : global::ProtoBuf.IExtensible
  {
    public pbEquipMove() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private int? _pos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos?? default(int); }
      set { _pos = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool posSpecified
    {
      get { return this._pos != null; }
      set { if (value == (this._pos== null)) this._pos = value ? this.pos : (int?)null; }
    }
    private bool ShouldSerializepos() { return posSpecified; }
    private void Resetpos() { posSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbGoodsChanged")]
  public partial class pbGoodsChanged : global::ProtoBuf.IExtensible
  {
    public pbGoodsChanged() {}
    
    private pb_15.pbGoodsList _added_list = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"added_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pb_15.pbGoodsList added_list
    {
      get { return _added_list; }
      set { _added_list = value; }
    }
    private pb_15.pbGoodsList _deleted_list = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"deleted_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pb_15.pbGoodsList deleted_list
    {
      get { return _deleted_list; }
      set { _deleted_list = value; }
    }
    private pb_15.pbGoodsList _updated_list = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"updated_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pb_15.pbGoodsList updated_list
    {
      get { return _updated_list; }
      set { _updated_list = value; }
    }
    private int? _update_timestamp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"update_timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int update_timestamp
    {
      get { return _update_timestamp?? default(int); }
      set { _update_timestamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool update_timestampSpecified
    {
      get { return this._update_timestamp != null; }
      set { if (value == (this._update_timestamp== null)) this._update_timestamp = value ? this.update_timestamp : (int?)null; }
    }
    private bool ShouldSerializeupdate_timestamp() { return update_timestampSpecified; }
    private void Resetupdate_timestamp() { update_timestampSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbEquipStrengthen")]
  public partial class pbEquipStrengthen : global::ProtoBuf.IExtensible
  {
    public pbEquipStrengthen() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private int? _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num?? default(int); }
      set { _num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numSpecified
    {
      get { return this._num != null; }
      set { if (value == (this._num== null)) this._num = value ? this.num : (int?)null; }
    }
    private bool ShouldSerializenum() { return numSpecified; }
    private void Resetnum() { numSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbEquipAddStar")]
  public partial class pbEquipAddStar : global::ProtoBuf.IExtensible
  {
    public pbEquipAddStar() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private int? _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num?? default(int); }
      set { _num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numSpecified
    {
      get { return this._num != null; }
      set { if (value == (this._num== null)) this._num = value ? this.num : (int?)null; }
    }
    private bool ShouldSerializenum() { return numSpecified; }
    private void Resetnum() { numSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbSmriti")]
  public partial class pbSmriti : global::ProtoBuf.IExtensible
  {
    public pbSmriti() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private int? _tid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tid
    {
      get { return _tid?? default(int); }
      set { _tid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool tidSpecified
    {
      get { return this._tid != null; }
      set { if (value == (this._tid== null)) this._tid = value ? this.tid : (int?)null; }
    }
    private bool ShouldSerializetid() { return tidSpecified; }
    private void Resettid() { tidSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbStoreProduct")]
  public partial class pbStoreProduct : global::ProtoBuf.IExtensible
  {
    public pbStoreProduct() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private string _product_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"product_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string product_id
    {
      get { return _product_id?? ""; }
      set { _product_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool product_idSpecified
    {
      get { return this._product_id != null; }
      set { if (value == (this._product_id== null)) this._product_id = value ? this.product_id : (string)null; }
    }
    private bool ShouldSerializeproduct_id() { return product_idSpecified; }
    private void Resetproduct_id() { product_idSpecified = false; }
    
    private int? _gold;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gold
    {
      get { return _gold?? default(int); }
      set { _gold = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool goldSpecified
    {
      get { return this._gold != null; }
      set { if (value == (this._gold== null)) this._gold = value ? this.gold : (int?)null; }
    }
    private bool ShouldSerializegold() { return goldSpecified; }
    private void Resetgold() { goldSpecified = false; }
    
    private int? _reward_gold;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"reward_gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int reward_gold
    {
      get { return _reward_gold?? default(int); }
      set { _reward_gold = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool reward_goldSpecified
    {
      get { return this._reward_gold != null; }
      set { if (value == (this._reward_gold== null)) this._reward_gold = value ? this.reward_gold : (int?)null; }
    }
    private bool ShouldSerializereward_gold() { return reward_goldSpecified; }
    private void Resetreward_gold() { reward_goldSpecified = false; }
    
    private int? _money;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int money
    {
      get { return _money?? default(int); }
      set { _money = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool moneySpecified
    {
      get { return this._money != null; }
      set { if (value == (this._money== null)) this._money = value ? this.money : (int?)null; }
    }
    private bool ShouldSerializemoney() { return moneySpecified; }
    private void Resetmoney() { moneySpecified = false; }
    
    private int? _icon;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int icon
    {
      get { return _icon?? default(int); }
      set { _icon = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool iconSpecified
    {
      get { return this._icon != null; }
      set { if (value == (this._icon== null)) this._icon = value ? this.icon : (int?)null; }
    }
    private bool ShouldSerializeicon() { return iconSpecified; }
    private void Reseticon() { iconSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbStoreProductList")]
  public partial class pbStoreProductList : global::ProtoBuf.IExtensible
  {
    public pbStoreProductList() {}
    
    private readonly global::System.Collections.Generic.List<pb_15.pbStoreProduct> _product_list = new global::System.Collections.Generic.List<pb_15.pbStoreProduct>();
    [global::ProtoBuf.ProtoMember(1, Name=@"product_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_15.pbStoreProduct> product_list
    {
      get { return _product_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbInlaidJewel")]
  public partial class pbInlaidJewel : global::ProtoBuf.IExtensible
  {
    public pbInlaidJewel() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private int? _tid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tid
    {
      get { return _tid?? default(int); }
      set { _tid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool tidSpecified
    {
      get { return this._tid != null; }
      set { if (value == (this._tid== null)) this._tid = value ? this.tid : (int?)null; }
    }
    private bool ShouldSerializetid() { return tidSpecified; }
    private void Resettid() { tidSpecified = false; }
    
    private int? _num;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num?? default(int); }
      set { _num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numSpecified
    {
      get { return this._num != null; }
      set { if (value == (this._num== null)) this._num = value ? this.num : (int?)null; }
    }
    private bool ShouldSerializenum() { return numSpecified; }
    private void Resetnum() { numSpecified = false; }
    
    private int? _pos;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos?? default(int); }
      set { _pos = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool posSpecified
    {
      get { return this._pos != null; }
      set { if (value == (this._pos== null)) this._pos = value ? this.pos : (int?)null; }
    }
    private bool ShouldSerializepos() { return posSpecified; }
    private void Resetpos() { posSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbShopItem")]
  public partial class pbShopItem : global::ProtoBuf.IExtensible
  {
    public pbShopItem() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private int? _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num?? default(int); }
      set { _num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numSpecified
    {
      get { return this._num != null; }
      set { if (value == (this._num== null)) this._num = value ? this.num : (int?)null; }
    }
    private bool ShouldSerializenum() { return numSpecified; }
    private void Resetnum() { numSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbShopMsg")]
  public partial class pbShopMsg : global::ProtoBuf.IExtensible
  {
    public pbShopMsg() {}
    
    private int? _base_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"base_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int base_id
    {
      get { return _base_id?? default(int); }
      set { _base_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool base_idSpecified
    {
      get { return this._base_id != null; }
      set { if (value == (this._base_id== null)) this._base_id = value ? this.base_id : (int?)null; }
    }
    private bool ShouldSerializebase_id() { return base_idSpecified; }
    private void Resetbase_id() { base_idSpecified = false; }
    
    private int? _is_buy;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"is_buy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int is_buy
    {
      get { return _is_buy?? default(int); }
      set { _is_buy = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool is_buySpecified
    {
      get { return this._is_buy != null; }
      set { if (value == (this._is_buy== null)) this._is_buy = value ? this.is_buy : (int?)null; }
    }
    private bool ShouldSerializeis_buy() { return is_buySpecified; }
    private void Resetis_buy() { is_buySpecified = false; }
    
    private int? _pos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos?? default(int); }
      set { _pos = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool posSpecified
    {
      get { return this._pos != null; }
      set { if (value == (this._pos== null)) this._pos = value ? this.pos : (int?)null; }
    }
    private bool ShouldSerializepos() { return posSpecified; }
    private void Resetpos() { posSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbSteriousShop")]
  public partial class pbSteriousShop : global::ProtoBuf.IExtensible
  {
    public pbSteriousShop() {}
    
    private readonly global::System.Collections.Generic.List<pb_15.pbShopMsg> _shop_list = new global::System.Collections.Generic.List<pb_15.pbShopMsg>();
    [global::ProtoBuf.ProtoMember(1, Name=@"shop_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_15.pbShopMsg> shop_list
    {
      get { return _shop_list; }
    }
  
    private int? _shop_refresh_num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"shop_refresh_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shop_refresh_num
    {
      get { return _shop_refresh_num?? default(int); }
      set { _shop_refresh_num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool shop_refresh_numSpecified
    {
      get { return this._shop_refresh_num != null; }
      set { if (value == (this._shop_refresh_num== null)) this._shop_refresh_num = value ? this.shop_refresh_num : (int?)null; }
    }
    private bool ShouldSerializeshop_refresh_num() { return shop_refresh_numSpecified; }
    private void Resetshop_refresh_num() { shop_refresh_numSpecified = false; }
    
    private int? _shop_last_refresh_time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"shop_last_refresh_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shop_last_refresh_time
    {
      get { return _shop_last_refresh_time?? default(int); }
      set { _shop_last_refresh_time = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool shop_last_refresh_timeSpecified
    {
      get { return this._shop_last_refresh_time != null; }
      set { if (value == (this._shop_last_refresh_time== null)) this._shop_last_refresh_time = value ? this.shop_last_refresh_time : (int?)null; }
    }
    private bool ShouldSerializeshop_last_refresh_time() { return shop_last_refresh_timeSpecified; }
    private void Resetshop_last_refresh_time() { shop_last_refresh_timeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbShopBuy")]
  public partial class pbShopBuy : global::ProtoBuf.IExtensible
  {
    public pbShopBuy() {}
    
    private int? _pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos?? default(int); }
      set { _pos = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool posSpecified
    {
      get { return this._pos != null; }
      set { if (value == (this._pos== null)) this._pos = value ? this.pos : (int?)null; }
    }
    private bool ShouldSerializepos() { return posSpecified; }
    private void Resetpos() { posSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbOrdinaryBuy")]
  public partial class pbOrdinaryBuy : global::ProtoBuf.IExtensible
  {
    public pbOrdinaryBuy() {}
    
    private int? _base_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"base_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int base_id
    {
      get { return _base_id?? default(int); }
      set { _base_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool base_idSpecified
    {
      get { return this._base_id != null; }
      set { if (value == (this._base_id== null)) this._base_id = value ? this.base_id : (int?)null; }
    }
    private bool ShouldSerializebase_id() { return base_idSpecified; }
    private void Resetbase_id() { base_idSpecified = false; }
    
    private int? _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num?? default(int); }
      set { _num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numSpecified
    {
      get { return this._num != null; }
      set { if (value == (this._num== null)) this._num = value ? this.num : (int?)null; }
    }
    private bool ShouldSerializenum() { return numSpecified; }
    private void Resetnum() { numSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbSellingShop")]
  public partial class pbSellingShop : global::ProtoBuf.IExtensible
  {
    public pbSellingShop() {}
    
    private int? _base_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"base_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int base_id
    {
      get { return _base_id?? default(int); }
      set { _base_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool base_idSpecified
    {
      get { return this._base_id != null; }
      set { if (value == (this._base_id== null)) this._base_id = value ? this.base_id : (int?)null; }
    }
    private bool ShouldSerializebase_id() { return base_idSpecified; }
    private void Resetbase_id() { base_idSpecified = false; }
    
    private int? _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num?? default(int); }
      set { _num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numSpecified
    {
      get { return this._num != null; }
      set { if (value == (this._num== null)) this._num = value ? this.num : (int?)null; }
    }
    private bool ShouldSerializenum() { return numSpecified; }
    private void Resetnum() { numSpecified = false; }
    
    private int? _buy_times;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"buy_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int buy_times
    {
      get { return _buy_times?? default(int); }
      set { _buy_times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool buy_timesSpecified
    {
      get { return this._buy_times != null; }
      set { if (value == (this._buy_times== null)) this._buy_times = value ? this.buy_times : (int?)null; }
    }
    private bool ShouldSerializebuy_times() { return buy_timesSpecified; }
    private void Resetbuy_times() { buy_timesSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbSellingList")]
  public partial class pbSellingList : global::ProtoBuf.IExtensible
  {
    public pbSellingList() {}
    
    private readonly global::System.Collections.Generic.List<pb_15.pbSellingShop> _shop_list = new global::System.Collections.Generic.List<pb_15.pbSellingShop>();
    [global::ProtoBuf.ProtoMember(1, Name=@"shop_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_15.pbSellingShop> shop_list
    {
      get { return _shop_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbActivityShopMsg")]
  public partial class pbActivityShopMsg : global::ProtoBuf.IExtensible
  {
    public pbActivityShopMsg() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private int? _activity_remain_num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"activity_remain_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int activity_remain_num
    {
      get { return _activity_remain_num?? default(int); }
      set { _activity_remain_num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool activity_remain_numSpecified
    {
      get { return this._activity_remain_num != null; }
      set { if (value == (this._activity_remain_num== null)) this._activity_remain_num = value ? this.activity_remain_num : (int?)null; }
    }
    private bool ShouldSerializeactivity_remain_num() { return activity_remain_numSpecified; }
    private void Resetactivity_remain_num() { activity_remain_numSpecified = false; }
    
    private int? _player_remain_num;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"player_remain_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_remain_num
    {
      get { return _player_remain_num?? default(int); }
      set { _player_remain_num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool player_remain_numSpecified
    {
      get { return this._player_remain_num != null; }
      set { if (value == (this._player_remain_num== null)) this._player_remain_num = value ? this.player_remain_num : (int?)null; }
    }
    private bool ShouldSerializeplayer_remain_num() { return player_remain_numSpecified; }
    private void Resetplayer_remain_num() { player_remain_numSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbActivityShop")]
  public partial class pbActivityShop : global::ProtoBuf.IExtensible
  {
    public pbActivityShop() {}
    
    private int? _timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timestamp
    {
      get { return _timestamp?? default(int); }
      set { _timestamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timestampSpecified
    {
      get { return this._timestamp != null; }
      set { if (value == (this._timestamp== null)) this._timestamp = value ? this.timestamp : (int?)null; }
    }
    private bool ShouldSerializetimestamp() { return timestampSpecified; }
    private void Resettimestamp() { timestampSpecified = false; }
    
    private int? _activity_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"activity_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int activity_id
    {
      get { return _activity_id?? default(int); }
      set { _activity_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool activity_idSpecified
    {
      get { return this._activity_id != null; }
      set { if (value == (this._activity_id== null)) this._activity_id = value ? this.activity_id : (int?)null; }
    }
    private bool ShouldSerializeactivity_id() { return activity_idSpecified; }
    private void Resetactivity_id() { activity_idSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<pb_15.pbActivityShopMsg> _shop_list = new global::System.Collections.Generic.List<pb_15.pbActivityShopMsg>();
    [global::ProtoBuf.ProtoMember(3, Name=@"shop_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_15.pbActivityShopMsg> shop_list
    {
      get { return _shop_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbUpgradeSkillCard")]
  public partial class pbUpgradeSkillCard : global::ProtoBuf.IExtensible
  {
    public pbUpgradeSkillCard() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<pb_common.pbGoodsInfo> _consume_list = new global::System.Collections.Generic.List<pb_common.pbGoodsInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"consume_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_common.pbGoodsInfo> consume_list
    {
      get { return _consume_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbChoujiangInfo")]
  public partial class pbChoujiangInfo : global::ProtoBuf.IExtensible
  {
    public pbChoujiangInfo() {}
    
    private int? _coin_timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"coin_timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coin_timestamp
    {
      get { return _coin_timestamp?? default(int); }
      set { _coin_timestamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool coin_timestampSpecified
    {
      get { return this._coin_timestamp != null; }
      set { if (value == (this._coin_timestamp== null)) this._coin_timestamp = value ? this.coin_timestamp : (int?)null; }
    }
    private bool ShouldSerializecoin_timestamp() { return coin_timestampSpecified; }
    private void Resetcoin_timestamp() { coin_timestampSpecified = false; }
    
    private int? _gold_timestamp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gold_timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gold_timestamp
    {
      get { return _gold_timestamp?? default(int); }
      set { _gold_timestamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool gold_timestampSpecified
    {
      get { return this._gold_timestamp != null; }
      set { if (value == (this._gold_timestamp== null)) this._gold_timestamp = value ? this.gold_timestamp : (int?)null; }
    }
    private bool ShouldSerializegold_timestamp() { return gold_timestampSpecified; }
    private void Resetgold_timestamp() { gold_timestampSpecified = false; }
    
    private int? _coin_free_num;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"coin_free_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coin_free_num
    {
      get { return _coin_free_num?? default(int); }
      set { _coin_free_num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool coin_free_numSpecified
    {
      get { return this._coin_free_num != null; }
      set { if (value == (this._coin_free_num== null)) this._coin_free_num = value ? this.coin_free_num : (int?)null; }
    }
    private bool ShouldSerializecoin_free_num() { return coin_free_numSpecified; }
    private void Resetcoin_free_num() { coin_free_numSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbChoujiang")]
  public partial class pbChoujiang : global::ProtoBuf.IExtensible
  {
    public pbChoujiang() {}
    
    private int? _money_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"money_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int money_type
    {
      get { return _money_type?? default(int); }
      set { _money_type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool money_typeSpecified
    {
      get { return this._money_type != null; }
      set { if (value == (this._money_type== null)) this._money_type = value ? this.money_type : (int?)null; }
    }
    private bool ShouldSerializemoney_type() { return money_typeSpecified; }
    private void Resetmoney_type() { money_typeSpecified = false; }
    
    private int? _buy_num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"buy_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int buy_num
    {
      get { return _buy_num?? default(int); }
      set { _buy_num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool buy_numSpecified
    {
      get { return this._buy_num != null; }
      set { if (value == (this._buy_num== null)) this._buy_num = value ? this.buy_num : (int?)null; }
    }
    private bool ShouldSerializebuy_num() { return buy_numSpecified; }
    private void Resetbuy_num() { buy_numSpecified = false; }
    
    private int? _is_free;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"is_free", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int is_free
    {
      get { return _is_free?? default(int); }
      set { _is_free = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool is_freeSpecified
    {
      get { return this._is_free != null; }
      set { if (value == (this._is_free== null)) this._is_free = value ? this.is_free : (int?)null; }
    }
    private bool ShouldSerializeis_free() { return is_freeSpecified; }
    private void Resetis_free() { is_freeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbChoujiangGoods")]
  public partial class pbChoujiangGoods : global::ProtoBuf.IExtensible
  {
    public pbChoujiangGoods() {}
    
    private int? _goods_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"goods_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int goods_id
    {
      get { return _goods_id?? default(int); }
      set { _goods_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool goods_idSpecified
    {
      get { return this._goods_id != null; }
      set { if (value == (this._goods_id== null)) this._goods_id = value ? this.goods_id : (int?)null; }
    }
    private bool ShouldSerializegoods_id() { return goods_idSpecified; }
    private void Resetgoods_id() { goods_idSpecified = false; }
    
    private int? _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num?? default(int); }
      set { _num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numSpecified
    {
      get { return this._num != null; }
      set { if (value == (this._num== null)) this._num = value ? this.num : (int?)null; }
    }
    private bool ShouldSerializenum() { return numSpecified; }
    private void Resetnum() { numSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbChoujiangResult")]
  public partial class pbChoujiangResult : global::ProtoBuf.IExtensible
  {
    public pbChoujiangResult() {}
    
    private readonly global::System.Collections.Generic.List<pb_common.pbGoodsInfo> _result_list = new global::System.Collections.Generic.List<pb_common.pbGoodsInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"result_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_common.pbGoodsInfo> result_list
    {
      get { return _result_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbGeneralStoreInfo")]
  public partial class pbGeneralStoreInfo : global::ProtoBuf.IExtensible
  {
    public pbGeneralStoreInfo() {}
    
    private int? _store_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"store_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int store_type
    {
      get { return _store_type?? default(int); }
      set { _store_type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool store_typeSpecified
    {
      get { return this._store_type != null; }
      set { if (value == (this._store_type== null)) this._store_type = value ? this.store_type : (int?)null; }
    }
    private bool ShouldSerializestore_type() { return store_typeSpecified; }
    private void Resetstore_type() { store_typeSpecified = false; }
    
    private pb_15.pbSteriousShop _shop_info = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"shop_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pb_15.pbSteriousShop shop_info
    {
      get { return _shop_info; }
      set { _shop_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbGeneralStoreBuy")]
  public partial class pbGeneralStoreBuy : global::ProtoBuf.IExtensible
  {
    public pbGeneralStoreBuy() {}
    
    private int? _store_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"store_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int store_type
    {
      get { return _store_type?? default(int); }
      set { _store_type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool store_typeSpecified
    {
      get { return this._store_type != null; }
      set { if (value == (this._store_type== null)) this._store_type = value ? this.store_type : (int?)null; }
    }
    private bool ShouldSerializestore_type() { return store_typeSpecified; }
    private void Resetstore_type() { store_typeSpecified = false; }
    
    private int? _pos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos?? default(int); }
      set { _pos = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool posSpecified
    {
      get { return this._pos != null; }
      set { if (value == (this._pos== null)) this._pos = value ? this.pos : (int?)null; }
    }
    private bool ShouldSerializepos() { return posSpecified; }
    private void Resetpos() { posSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbSkillId")]
  public partial class pbSkillId : global::ProtoBuf.IExtensible
  {
    public pbSkillId() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbSkillIdList")]
  public partial class pbSkillIdList : global::ProtoBuf.IExtensible
  {
    public pbSkillIdList() {}
    
    private readonly global::System.Collections.Generic.List<pb_15.pbSkillId> _List = new global::System.Collections.Generic.List<pb_15.pbSkillId>();
    [global::ProtoBuf.ProtoMember(1, Name=@"List", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_15.pbSkillId> List
    {
      get { return _List; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbReward")]
  public partial class pbReward : global::ProtoBuf.IExtensible
  {
    public pbReward() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private int? _goods_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"goods_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int goods_id
    {
      get { return _goods_id?? default(int); }
      set { _goods_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool goods_idSpecified
    {
      get { return this._goods_id != null; }
      set { if (value == (this._goods_id== null)) this._goods_id = value ? this.goods_id : (int?)null; }
    }
    private bool ShouldSerializegoods_id() { return goods_idSpecified; }
    private void Resetgoods_id() { goods_idSpecified = false; }
    
    private int? _num;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num?? default(int); }
      set { _num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numSpecified
    {
      get { return this._num != null; }
      set { if (value == (this._num== null)) this._num = value ? this.num : (int?)null; }
    }
    private bool ShouldSerializenum() { return numSpecified; }
    private void Resetnum() { numSpecified = false; }
    
    private int? _bind;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bind", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bind
    {
      get { return _bind?? default(int); }
      set { _bind = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool bindSpecified
    {
      get { return this._bind != null; }
      set { if (value == (this._bind== null)) this._bind = value ? this.bind : (int?)null; }
    }
    private bool ShouldSerializebind() { return bindSpecified; }
    private void Resetbind() { bindSpecified = false; }
    
    private int? _type;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type?? default(int); }
      set { _type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return this._type != null; }
      set { if (value == (this._type== null)) this._type = value ? this.type : (int?)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    
    private int? _day;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"day", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int day
    {
      get { return _day?? default(int); }
      set { _day = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool daySpecified
    {
      get { return this._day != null; }
      set { if (value == (this._day== null)) this._day = value ? this.day : (int?)null; }
    }
    private bool ShouldSerializeday() { return daySpecified; }
    private void Resetday() { daySpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbRewardList")]
  public partial class pbRewardList : global::ProtoBuf.IExtensible
  {
    public pbRewardList() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private int? _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type?? default(int); }
      set { _type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return this._type != null; }
      set { if (value == (this._type== null)) this._type = value ? this.type : (int?)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    
    private int? _timestamp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timestamp
    {
      get { return _timestamp?? default(int); }
      set { _timestamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timestampSpecified
    {
      get { return this._timestamp != null; }
      set { if (value == (this._timestamp== null)) this._timestamp = value ? this.timestamp : (int?)null; }
    }
    private bool ShouldSerializetimestamp() { return timestampSpecified; }
    private void Resettimestamp() { timestampSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<pb_15.pbReward> _reward_list = new global::System.Collections.Generic.List<pb_15.pbReward>();
    [global::ProtoBuf.ProtoMember(5, Name=@"reward_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_15.pbReward> reward_list
    {
      get { return _reward_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}