//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: pb_19.proto
// Note: requires additional types generated from: pb_common.proto
namespace pb_19
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbMailGoods")]
  public partial class pbMailGoods : global::ProtoBuf.IExtensible
  {
    public pbMailGoods() {}
    
    private long? _goodsid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"goodsid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long goodsid
    {
      get { return _goodsid?? default(long); }
      set { _goodsid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool goodsidSpecified
    {
      get { return this._goodsid != null; }
      set { if (value == (this._goodsid== null)) this._goodsid = value ? this.goodsid : (long?)null; }
    }
    private bool ShouldSerializegoodsid() { return goodsidSpecified; }
    private void Resetgoodsid() { goodsidSpecified = false; }
    
    private int? _goodsum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"goodsum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int goodsum
    {
      get { return _goodsum?? default(int); }
      set { _goodsum = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool goodsumSpecified
    {
      get { return this._goodsum != null; }
      set { if (value == (this._goodsum== null)) this._goodsum = value ? this.goodsum : (int?)null; }
    }
    private bool ShouldSerializegoodsum() { return goodsumSpecified; }
    private void Resetgoodsum() { goodsumSpecified = false; }
    
    private int? _position;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int position
    {
      get { return _position?? default(int); }
      set { _position = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool positionSpecified
    {
      get { return this._position != null; }
      set { if (value == (this._position== null)) this._position = value ? this.position : (int?)null; }
    }
    private bool ShouldSerializeposition() { return positionSpecified; }
    private void Resetposition() { positionSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbMail")]
  public partial class pbMail : global::ProtoBuf.IExtensible
  {
    public pbMail() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private int? _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type?? default(int); }
      set { _type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return this._type != null; }
      set { if (value == (this._type== null)) this._type = value ? this.type : (int?)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    
    private int? _timestamp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timestamp
    {
      get { return _timestamp?? default(int); }
      set { _timestamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timestampSpecified
    {
      get { return this._timestamp != null; }
      set { if (value == (this._timestamp== null)) this._timestamp = value ? this.timestamp : (int?)null; }
    }
    private bool ShouldSerializetimestamp() { return timestampSpecified; }
    private void Resettimestamp() { timestampSpecified = false; }
    
    private string _sender_name;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sender_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sender_name
    {
      get { return _sender_name?? ""; }
      set { _sender_name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sender_nameSpecified
    {
      get { return this._sender_name != null; }
      set { if (value == (this._sender_name== null)) this._sender_name = value ? this.sender_name : (string)null; }
    }
    private bool ShouldSerializesender_name() { return sender_nameSpecified; }
    private void Resetsender_name() { sender_nameSpecified = false; }
    
    private long? _sender_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sender_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long sender_id
    {
      get { return _sender_id?? default(long); }
      set { _sender_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sender_idSpecified
    {
      get { return this._sender_id != null; }
      set { if (value == (this._sender_id== null)) this._sender_id = value ? this.sender_id : (long?)null; }
    }
    private bool ShouldSerializesender_id() { return sender_idSpecified; }
    private void Resetsender_id() { sender_idSpecified = false; }
    
    private long? _recv_id;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"recv_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long recv_id
    {
      get { return _recv_id?? default(long); }
      set { _recv_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool recv_idSpecified
    {
      get { return this._recv_id != null; }
      set { if (value == (this._recv_id== null)) this._recv_id = value ? this.recv_id : (long?)null; }
    }
    private bool ShouldSerializerecv_id() { return recv_idSpecified; }
    private void Resetrecv_id() { recv_idSpecified = false; }
    
    private string _recv_name;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"recv_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string recv_name
    {
      get { return _recv_name?? ""; }
      set { _recv_name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool recv_nameSpecified
    {
      get { return this._recv_name != null; }
      set { if (value == (this._recv_name== null)) this._recv_name = value ? this.recv_name : (string)null; }
    }
    private bool ShouldSerializerecv_name() { return recv_nameSpecified; }
    private void Resetrecv_name() { recv_nameSpecified = false; }
    
    private string _title;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string title
    {
      get { return _title?? ""; }
      set { _title = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool titleSpecified
    {
      get { return this._title != null; }
      set { if (value == (this._title== null)) this._title = value ? this.title : (string)null; }
    }
    private bool ShouldSerializetitle() { return titleSpecified; }
    private void Resettitle() { titleSpecified = false; }
    
    private string _content;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content?? ""; }
      set { _content = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool contentSpecified
    {
      get { return this._content != null; }
      set { if (value == (this._content== null)) this._content = value ? this.content : (string)null; }
    }
    private bool ShouldSerializecontent() { return contentSpecified; }
    private void Resetcontent() { contentSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<pb_19.pbMailGoods> _goodslist = new global::System.Collections.Generic.List<pb_19.pbMailGoods>();
    [global::ProtoBuf.ProtoMember(10, Name=@"goodslist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_19.pbMailGoods> goodslist
    {
      get { return _goodslist; }
    }
  
    private int? _state;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state?? default(int); }
      set { _state = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool stateSpecified
    {
      get { return this._state != null; }
      set { if (value == (this._state== null)) this._state = value ? this.state : (int?)null; }
    }
    private bool ShouldSerializestate() { return stateSpecified; }
    private void Resetstate() { stateSpecified = false; }
    
    private string _battle_report;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"battle_report", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string battle_report
    {
      get { return _battle_report?? ""; }
      set { _battle_report = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool battle_reportSpecified
    {
      get { return this._battle_report != null; }
      set { if (value == (this._battle_report== null)) this._battle_report = value ? this.battle_report : (string)null; }
    }
    private bool ShouldSerializebattle_report() { return battle_reportSpecified; }
    private void Resetbattle_report() { battle_reportSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbMailList")]
  public partial class pbMailList : global::ProtoBuf.IExtensible
  {
    public pbMailList() {}
    
    private readonly global::System.Collections.Generic.List<pb_19.pbMail> _update_list = new global::System.Collections.Generic.List<pb_19.pbMail>();
    [global::ProtoBuf.ProtoMember(1, Name=@"update_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_19.pbMail> update_list
    {
      get { return _update_list; }
    }
  
    private readonly global::System.Collections.Generic.List<pb_19.pbMail> _delete_list = new global::System.Collections.Generic.List<pb_19.pbMail>();
    [global::ProtoBuf.ProtoMember(2, Name=@"delete_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_19.pbMail> delete_list
    {
      get { return _delete_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}