//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: pb_11.proto
namespace pb_11
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbChat")]
  public partial class pbChat : global::ProtoBuf.IExtensible
  {
    public pbChat() {}
    
    private int? _id_n;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id_n", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id_n
    {
      get { return _id_n?? default(int); }
      set { _id_n = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool id_nSpecified
    {
      get { return this._id_n != null; }
      set { if (value == (this._id_n== null)) this._id_n = value ? this.id_n : (int?)null; }
    }
    private bool ShouldSerializeid_n() { return id_nSpecified; }
    private void Resetid_n() { id_nSpecified = false; }
    
    private int? _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type?? default(int); }
      set { _type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return this._type != null; }
      set { if (value == (this._type== null)) this._type = value ? this.type : (int?)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private long? _recv_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"recv_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long recv_id
    {
      get { return _recv_id?? default(long); }
      set { _recv_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool recv_idSpecified
    {
      get { return this._recv_id != null; }
      set { if (value == (this._recv_id== null)) this._recv_id = value ? this.recv_id : (long?)null; }
    }
    private bool ShouldSerializerecv_id() { return recv_idSpecified; }
    private void Resetrecv_id() { recv_idSpecified = false; }
    
    private long? _send_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"send_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long send_id
    {
      get { return _send_id?? default(long); }
      set { _send_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool send_idSpecified
    {
      get { return this._send_id != null; }
      set { if (value == (this._send_id== null)) this._send_id = value ? this.send_id : (long?)null; }
    }
    private bool ShouldSerializesend_id() { return send_idSpecified; }
    private void Resetsend_id() { send_idSpecified = false; }
    
    private string _nickname;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickname
    {
      get { return _nickname?? ""; }
      set { _nickname = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nicknameSpecified
    {
      get { return this._nickname != null; }
      set { if (value == (this._nickname== null)) this._nickname = value ? this.nickname : (string)null; }
    }
    private bool ShouldSerializenickname() { return nicknameSpecified; }
    private void Resetnickname() { nicknameSpecified = false; }
    
    private int? _lv;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lv
    {
      get { return _lv?? default(int); }
      set { _lv = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lvSpecified
    {
      get { return this._lv != null; }
      set { if (value == (this._lv== null)) this._lv = value ? this.lv : (int?)null; }
    }
    private bool ShouldSerializelv() { return lvSpecified; }
    private void Resetlv() { lvSpecified = false; }
    
    private int? _career;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"career", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int career
    {
      get { return _career?? default(int); }
      set { _career = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool careerSpecified
    {
      get { return this._career != null; }
      set { if (value == (this._career== null)) this._career = value ? this.career : (int?)null; }
    }
    private bool ShouldSerializecareer() { return careerSpecified; }
    private void Resetcareer() { careerSpecified = false; }
    
    private int? _vip;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int vip
    {
      get { return _vip?? default(int); }
      set { _vip = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool vipSpecified
    {
      get { return this._vip != null; }
      set { if (value == (this._vip== null)) this._vip = value ? this.vip : (int?)null; }
    }
    private bool ShouldSerializevip() { return vipSpecified; }
    private void Resetvip() { vipSpecified = false; }
    
    private string _msg;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg?? ""; }
      set { _msg = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool msgSpecified
    {
      get { return this._msg != null; }
      set { if (value == (this._msg== null)) this._msg = value ? this.msg : (string)null; }
    }
    private bool ShouldSerializemsg() { return msgSpecified; }
    private void Resetmsg() { msgSpecified = false; }
    
    private int? _timestamp;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timestamp
    {
      get { return _timestamp?? default(int); }
      set { _timestamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timestampSpecified
    {
      get { return this._timestamp != null; }
      set { if (value == (this._timestamp== null)) this._timestamp = value ? this.timestamp : (int?)null; }
    }
    private bool ShouldSerializetimestamp() { return timestampSpecified; }
    private void Resettimestamp() { timestampSpecified = false; }
    
    private int? _league_id;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"league_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int league_id
    {
      get { return _league_id?? default(int); }
      set { _league_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool league_idSpecified
    {
      get { return this._league_id != null; }
      set { if (value == (this._league_id== null)) this._league_id = value ? this.league_id : (int?)null; }
    }
    private bool ShouldSerializeleague_id() { return league_idSpecified; }
    private void Resetleague_id() { league_idSpecified = false; }
    
    private int? _gold_num;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"gold_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gold_num
    {
      get { return _gold_num?? default(int); }
      set { _gold_num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool gold_numSpecified
    {
      get { return this._gold_num != null; }
      set { if (value == (this._gold_num== null)) this._gold_num = value ? this.gold_num : (int?)null; }
    }
    private bool ShouldSerializegold_num() { return gold_numSpecified; }
    private void Resetgold_num() { gold_numSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbId32")]
  public partial class pbId32 : global::ProtoBuf.IExtensible
  {
    public pbId32() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbChatList")]
  public partial class pbChatList : global::ProtoBuf.IExtensible
  {
    public pbChatList() {}
    
    private readonly global::System.Collections.Generic.List<pb_11.pbChat> _update_list = new global::System.Collections.Generic.List<pb_11.pbChat>();
    [global::ProtoBuf.ProtoMember(1, Name=@"update_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_11.pbChat> update_list
    {
      get { return _update_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PbPrivate")]
  public partial class PbPrivate : global::ProtoBuf.IExtensible
  {
    public PbPrivate() {}
    
    private readonly global::System.Collections.Generic.List<pb_11.pbChat> _send_list = new global::System.Collections.Generic.List<pb_11.pbChat>();
    [global::ProtoBuf.ProtoMember(1, Name=@"send_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_11.pbChat> send_list
    {
      get { return _send_list; }
    }
  
    private readonly global::System.Collections.Generic.List<pb_11.pbChat> _recv_list = new global::System.Collections.Generic.List<pb_11.pbChat>();
    [global::ProtoBuf.ProtoMember(2, Name=@"recv_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_11.pbChat> recv_list
    {
      get { return _recv_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbNewMsg")]
  public partial class pbNewMsg : global::ProtoBuf.IExtensible
  {
    public pbNewMsg() {}
    
    private readonly global::System.Collections.Generic.List<int> _send_list = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"send_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> send_list
    {
      get { return _send_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbFeedBackMsg")]
  public partial class pbFeedBackMsg : global::ProtoBuf.IExtensible
  {
    public pbFeedBackMsg() {}
    
    private string _title;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string title
    {
      get { return _title?? ""; }
      set { _title = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool titleSpecified
    {
      get { return this._title != null; }
      set { if (value == (this._title== null)) this._title = value ? this.title : (string)null; }
    }
    private bool ShouldSerializetitle() { return titleSpecified; }
    private void Resettitle() { titleSpecified = false; }
    
    private string _content;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content?? ""; }
      set { _content = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool contentSpecified
    {
      get { return this._content != null; }
      set { if (value == (this._content== null)) this._content = value ? this.content : (string)null; }
    }
    private bool ShouldSerializecontent() { return contentSpecified; }
    private void Resetcontent() { contentSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}