//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: pb_12.proto
// Note: requires additional types generated from: pb_common.proto
namespace pb_12
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbDungeonReward")]
  public partial class pbDungeonReward : global::ProtoBuf.IExtensible
  {
    public pbDungeonReward() {}
    
    private int? _goods_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"goods_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int goods_id
    {
      get { return _goods_id?? default(int); }
      set { _goods_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool goods_idSpecified
    {
      get { return this._goods_id != null; }
      set { if (value == (this._goods_id== null)) this._goods_id = value ? this.goods_id : (int?)null; }
    }
    private bool ShouldSerializegoods_id() { return goods_idSpecified; }
    private void Resetgoods_id() { goods_idSpecified = false; }
    
    private int? _number;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int number
    {
      get { return _number?? default(int); }
      set { _number = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numberSpecified
    {
      get { return this._number != null; }
      set { if (value == (this._number== null)) this._number = value ? this.number : (int?)null; }
    }
    private bool ShouldSerializenumber() { return numberSpecified; }
    private void Resetnumber() { numberSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbHitRewardDetail")]
  public partial class pbHitRewardDetail : global::ProtoBuf.IExtensible
  {
    public pbHitRewardDetail() {}
    
    private int? _combo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"combo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int combo
    {
      get { return _combo?? default(int); }
      set { _combo = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool comboSpecified
    {
      get { return this._combo != null; }
      set { if (value == (this._combo== null)) this._combo = value ? this.combo : (int?)null; }
    }
    private bool ShouldSerializecombo() { return comboSpecified; }
    private void Resetcombo() { comboSpecified = false; }
    
    private int? _number;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int number
    {
      get { return _number?? default(int); }
      set { _number = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numberSpecified
    {
      get { return this._number != null; }
      set { if (value == (this._number== null)) this._number = value ? this.number : (int?)null; }
    }
    private bool ShouldSerializenumber() { return numberSpecified; }
    private void Resetnumber() { numberSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbSubDungeon")]
  public partial class pbSubDungeon : global::ProtoBuf.IExtensible
  {
    public pbSubDungeon() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<int> _create_portal = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"create_portal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> create_portal
    {
      get { return _create_portal; }
    }
  
    private readonly global::System.Collections.Generic.List<pb_12.pbWaveMonster> _wave_monster = new global::System.Collections.Generic.List<pb_12.pbWaveMonster>();
    [global::ProtoBuf.ProtoMember(3, Name=@"wave_monster", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_12.pbWaveMonster> wave_monster
    {
      get { return _wave_monster; }
    }
  
    private readonly global::System.Collections.Generic.List<pb_12.pbWaveCreature> _wave_creature = new global::System.Collections.Generic.List<pb_12.pbWaveCreature>();
    [global::ProtoBuf.ProtoMember(4, Name=@"wave_creature", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_12.pbWaveCreature> wave_creature
    {
      get { return _wave_creature; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbWaveCreature")]
  public partial class pbWaveCreature : global::ProtoBuf.IExtensible
  {
    public pbWaveCreature() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<pb_12.pbDungeonCreature> _creature_info = new global::System.Collections.Generic.List<pb_12.pbDungeonCreature>();
    [global::ProtoBuf.ProtoMember(2, Name=@"creature_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_12.pbDungeonCreature> creature_info
    {
      get { return _creature_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbWaveMonster")]
  public partial class pbWaveMonster : global::ProtoBuf.IExtensible
  {
    public pbWaveMonster() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<pb_12.pbDungeonMonster> _monster_info = new global::System.Collections.Generic.List<pb_12.pbDungeonMonster>();
    [global::ProtoBuf.ProtoMember(2, Name=@"monster_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_12.pbDungeonMonster> monster_info
    {
      get { return _monster_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbDungeonMonster")]
  public partial class pbDungeonMonster : global::ProtoBuf.IExtensible
  {
    public pbDungeonMonster() {}
    
    private int? _monster_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"monster_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int monster_id
    {
      get { return _monster_id?? default(int); }
      set { _monster_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool monster_idSpecified
    {
      get { return this._monster_id != null; }
      set { if (value == (this._monster_id== null)) this._monster_id = value ? this.monster_id : (int?)null; }
    }
    private bool ShouldSerializemonster_id() { return monster_idSpecified; }
    private void Resetmonster_id() { monster_idSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<pb_12.pbMonsterDrop> _monster_drop = new global::System.Collections.Generic.List<pb_12.pbMonsterDrop>();
    [global::ProtoBuf.ProtoMember(2, Name=@"monster_drop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_12.pbMonsterDrop> monster_drop
    {
      get { return _monster_drop; }
    }
  
    private int? _create_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"create_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int create_id
    {
      get { return _create_id?? default(int); }
      set { _create_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool create_idSpecified
    {
      get { return this._create_id != null; }
      set { if (value == (this._create_id== null)) this._create_id = value ? this.create_id : (int?)null; }
    }
    private bool ShouldSerializecreate_id() { return create_idSpecified; }
    private void Resetcreate_id() { create_idSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbMonsterDrop")]
  public partial class pbMonsterDrop : global::ProtoBuf.IExtensible
  {
    public pbMonsterDrop() {}
    
    private int? _goods_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"goods_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int goods_id
    {
      get { return _goods_id?? default(int); }
      set { _goods_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool goods_idSpecified
    {
      get { return this._goods_id != null; }
      set { if (value == (this._goods_id== null)) this._goods_id = value ? this.goods_id : (int?)null; }
    }
    private bool ShouldSerializegoods_id() { return goods_idSpecified; }
    private void Resetgoods_id() { goods_idSpecified = false; }
    
    private int? _number;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int number
    {
      get { return _number?? default(int); }
      set { _number = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numberSpecified
    {
      get { return this._number != null; }
      set { if (value == (this._number== null)) this._number = value ? this.number : (int?)null; }
    }
    private bool ShouldSerializenumber() { return numberSpecified; }
    private void Resetnumber() { numberSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbDungeonCreature")]
  public partial class pbDungeonCreature : global::ProtoBuf.IExtensible
  {
    public pbDungeonCreature() {}
    
    private int? _create_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"create_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int create_id
    {
      get { return _create_id?? default(int); }
      set { _create_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool create_idSpecified
    {
      get { return this._create_id != null; }
      set { if (value == (this._create_id== null)) this._create_id = value ? this.create_id : (int?)null; }
    }
    private bool ShouldSerializecreate_id() { return create_idSpecified; }
    private void Resetcreate_id() { create_idSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<pb_12.pbCreatureDrop> _creature_drop = new global::System.Collections.Generic.List<pb_12.pbCreatureDrop>();
    [global::ProtoBuf.ProtoMember(2, Name=@"creature_drop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_12.pbCreatureDrop> creature_drop
    {
      get { return _creature_drop; }
    }
  
    private int? _creature_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"creature_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int creature_id
    {
      get { return _creature_id?? default(int); }
      set { _creature_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool creature_idSpecified
    {
      get { return this._creature_id != null; }
      set { if (value == (this._creature_id== null)) this._creature_id = value ? this.creature_id : (int?)null; }
    }
    private bool ShouldSerializecreature_id() { return creature_idSpecified; }
    private void Resetcreature_id() { creature_idSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbCreatureDrop")]
  public partial class pbCreatureDrop : global::ProtoBuf.IExtensible
  {
    public pbCreatureDrop() {}
    
    private int? _goods_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"goods_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int goods_id
    {
      get { return _goods_id?? default(int); }
      set { _goods_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool goods_idSpecified
    {
      get { return this._goods_id != null; }
      set { if (value == (this._goods_id== null)) this._goods_id = value ? this.goods_id : (int?)null; }
    }
    private bool ShouldSerializegoods_id() { return goods_idSpecified; }
    private void Resetgoods_id() { goods_idSpecified = false; }
    
    private int? _number;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int number
    {
      get { return _number?? default(int); }
      set { _number = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numberSpecified
    {
      get { return this._number != null; }
      set { if (value == (this._number== null)) this._number = value ? this.number : (int?)null; }
    }
    private bool ShouldSerializenumber() { return numberSpecified; }
    private void Resetnumber() { numberSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbDungeon")]
  public partial class pbDungeon : global::ProtoBuf.IExtensible
  {
    public pbDungeon() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private int? _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type?? default(int); }
      set { _type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return this._type != null; }
      set { if (value == (this._type== null)) this._type = value ? this.type : (int?)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    
    private int? _is_extra;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"is_extra", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int is_extra
    {
      get { return _is_extra?? default(int); }
      set { _is_extra = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool is_extraSpecified
    {
      get { return this._is_extra != null; }
      set { if (value == (this._is_extra== null)) this._is_extra = value ? this.is_extra : (int?)null; }
    }
    private bool ShouldSerializeis_extra() { return is_extraSpecified; }
    private void Resetis_extra() { is_extraSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<pb_12.pbDungeonReward> _reward = new global::System.Collections.Generic.List<pb_12.pbDungeonReward>();
    [global::ProtoBuf.ProtoMember(4, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_12.pbDungeonReward> reward
    {
      get { return _reward; }
    }
  
    private readonly global::System.Collections.Generic.List<pb_12.pbDungeonReward> _extra_reward = new global::System.Collections.Generic.List<pb_12.pbDungeonReward>();
    [global::ProtoBuf.ProtoMember(5, Name=@"extra_reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_12.pbDungeonReward> extra_reward
    {
      get { return _extra_reward; }
    }
  
    private readonly global::System.Collections.Generic.List<pb_12.pbDungeonReward> _special_reward = new global::System.Collections.Generic.List<pb_12.pbDungeonReward>();
    [global::ProtoBuf.ProtoMember(6, Name=@"special_reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_12.pbDungeonReward> special_reward
    {
      get { return _special_reward; }
    }
  
    private int? _state;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state?? default(int); }
      set { _state = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool stateSpecified
    {
      get { return this._state != null; }
      set { if (value == (this._state== null)) this._state = value ? this.state : (int?)null; }
    }
    private bool ShouldSerializestate() { return stateSpecified; }
    private void Resetstate() { stateSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<pb_12.pbDungeonReward> _activity_dungeon_reward = new global::System.Collections.Generic.List<pb_12.pbDungeonReward>();
    [global::ProtoBuf.ProtoMember(8, Name=@"activity_dungeon_reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_12.pbDungeonReward> activity_dungeon_reward
    {
      get { return _activity_dungeon_reward; }
    }
  
    private readonly global::System.Collections.Generic.List<pb_12.pbSubDungeon> _dungeon_info = new global::System.Collections.Generic.List<pb_12.pbSubDungeon>();
    [global::ProtoBuf.ProtoMember(9, Name=@"dungeon_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_12.pbSubDungeon> dungeon_info
    {
      get { return _dungeon_info; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _sub_route = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"sub_route", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> sub_route
    {
      get { return _sub_route; }
    }
  
    private int? _score;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score?? default(int); }
      set { _score = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool scoreSpecified
    {
      get { return this._score != null; }
      set { if (value == (this._score== null)) this._score = value ? this.score : (int?)null; }
    }
    private bool ShouldSerializescore() { return scoreSpecified; }
    private void Resetscore() { scoreSpecified = false; }
    
    private int? _pass_time;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"pass_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pass_time
    {
      get { return _pass_time?? default(int); }
      set { _pass_time = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool pass_timeSpecified
    {
      get { return this._pass_time != null; }
      set { if (value == (this._pass_time== null)) this._pass_time = value ? this.pass_time : (int?)null; }
    }
    private bool ShouldSerializepass_time() { return pass_timeSpecified; }
    private void Resetpass_time() { pass_timeSpecified = false; }
    
    private int? _relive_times;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"relive_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int relive_times
    {
      get { return _relive_times?? default(int); }
      set { _relive_times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool relive_timesSpecified
    {
      get { return this._relive_times != null; }
      set { if (value == (this._relive_times== null)) this._relive_times = value ? this.relive_times : (int?)null; }
    }
    private bool ShouldSerializerelive_times() { return relive_timesSpecified; }
    private void Resetrelive_times() { relive_timesSpecified = false; }
    
    private int? _team_num;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"team_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int team_num
    {
      get { return _team_num?? default(int); }
      set { _team_num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool team_numSpecified
    {
      get { return this._team_num != null; }
      set { if (value == (this._team_num== null)) this._team_num = value ? this.team_num : (int?)null; }
    }
    private bool ShouldSerializeteam_num() { return team_numSpecified; }
    private void Resetteam_num() { team_numSpecified = false; }
    
    private int? _team_type;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"team_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int team_type
    {
      get { return _team_type?? default(int); }
      set { _team_type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool team_typeSpecified
    {
      get { return this._team_type != null; }
      set { if (value == (this._team_type== null)) this._team_type = value ? this.team_type : (int?)null; }
    }
    private bool ShouldSerializeteam_type() { return team_typeSpecified; }
    private void Resetteam_type() { team_typeSpecified = false; }
    
    private int? _cur_sub_dungeon;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"cur_sub_dungeon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cur_sub_dungeon
    {
      get { return _cur_sub_dungeon?? default(int); }
      set { _cur_sub_dungeon = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool cur_sub_dungeonSpecified
    {
      get { return this._cur_sub_dungeon != null; }
      set { if (value == (this._cur_sub_dungeon== null)) this._cur_sub_dungeon = value ? this.cur_sub_dungeon : (int?)null; }
    }
    private bool ShouldSerializecur_sub_dungeon() { return cur_sub_dungeonSpecified; }
    private void Resetcur_sub_dungeon() { cur_sub_dungeonSpecified = false; }
    
    private int? _boss_flag;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"boss_flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int boss_flag
    {
      get { return _boss_flag?? default(int); }
      set { _boss_flag = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool boss_flagSpecified
    {
      get { return this._boss_flag != null; }
      set { if (value == (this._boss_flag== null)) this._boss_flag = value ? this.boss_flag : (int?)null; }
    }
    private bool ShouldSerializeboss_flag() { return boss_flagSpecified; }
    private void Resetboss_flag() { boss_flagSpecified = false; }
    
    private int? _team_flag;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"team_flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int team_flag
    {
      get { return _team_flag?? default(int); }
      set { _team_flag = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool team_flagSpecified
    {
      get { return this._team_flag != null; }
      set { if (value == (this._team_flag== null)) this._team_flag = value ? this.team_flag : (int?)null; }
    }
    private bool ShouldSerializeteam_flag() { return team_flagSpecified; }
    private void Resetteam_flag() { team_flagSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<int> _target_list = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(19, Name=@"target_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> target_list
    {
      get { return _target_list; }
    }
  
    private readonly global::System.Collections.Generic.List<pb_12.pbDungeonReward> _hit_reward = new global::System.Collections.Generic.List<pb_12.pbDungeonReward>();
    [global::ProtoBuf.ProtoMember(20, Name=@"hit_reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_12.pbDungeonReward> hit_reward
    {
      get { return _hit_reward; }
    }
  
    private readonly global::System.Collections.Generic.List<pb_12.pbHitRewardDetail> _hit_reward_detail = new global::System.Collections.Generic.List<pb_12.pbHitRewardDetail>();
    [global::ProtoBuf.ProtoMember(21, Name=@"hit_reward_detail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_12.pbHitRewardDetail> hit_reward_detail
    {
      get { return _hit_reward_detail; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbFlipCard")]
  public partial class pbFlipCard : global::ProtoBuf.IExtensible
  {
    public pbFlipCard() {}
    
    private int? _dungeon_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dungeon_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dungeon_id
    {
      get { return _dungeon_id?? default(int); }
      set { _dungeon_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dungeon_idSpecified
    {
      get { return this._dungeon_id != null; }
      set { if (value == (this._dungeon_id== null)) this._dungeon_id = value ? this.dungeon_id : (int?)null; }
    }
    private bool ShouldSerializedungeon_id() { return dungeon_idSpecified; }
    private void Resetdungeon_id() { dungeon_idSpecified = false; }
    
    private int? _card_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"card_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card_type
    {
      get { return _card_type?? default(int); }
      set { _card_type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool card_typeSpecified
    {
      get { return this._card_type != null; }
      set { if (value == (this._card_type== null)) this._card_type = value ? this.card_type : (int?)null; }
    }
    private bool ShouldSerializecard_type() { return card_typeSpecified; }
    private void Resetcard_type() { card_typeSpecified = false; }
    
    private pb_12.pbDungeonReward _reward = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pb_12.pbDungeonReward reward
    {
      get { return _reward; }
      set { _reward = value; }
    }
    private int? _pos;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos?? default(int); }
      set { _pos = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool posSpecified
    {
      get { return this._pos != null; }
      set { if (value == (this._pos== null)) this._pos = value ? this.pos : (int?)null; }
    }
    private bool ShouldSerializepos() { return posSpecified; }
    private void Resetpos() { posSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbChallengeDungeon")]
  public partial class pbChallengeDungeon : global::ProtoBuf.IExtensible
  {
    public pbChallengeDungeon() {}
    
    private int? _dungeon_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dungeon_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dungeon_id
    {
      get { return _dungeon_id?? default(int); }
      set { _dungeon_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dungeon_idSpecified
    {
      get { return this._dungeon_id != null; }
      set { if (value == (this._dungeon_id== null)) this._dungeon_id = value ? this.dungeon_id : (int?)null; }
    }
    private bool ShouldSerializedungeon_id() { return dungeon_idSpecified; }
    private void Resetdungeon_id() { dungeon_idSpecified = false; }
    
    private int? _next_dungeon_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"next_dungeon_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int next_dungeon_id
    {
      get { return _next_dungeon_id?? default(int); }
      set { _next_dungeon_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool next_dungeon_idSpecified
    {
      get { return this._next_dungeon_id != null; }
      set { if (value == (this._next_dungeon_id== null)) this._next_dungeon_id = value ? this.next_dungeon_id : (int?)null; }
    }
    private bool ShouldSerializenext_dungeon_id() { return next_dungeon_idSpecified; }
    private void Resetnext_dungeon_id() { next_dungeon_idSpecified = false; }
    
    private int? _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type?? default(int); }
      set { _type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return this._type != null; }
      set { if (value == (this._type== null)) this._type = value ? this.type : (int?)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<pb_12.pbDungeonReward> _reward = new global::System.Collections.Generic.List<pb_12.pbDungeonReward>();
    [global::ProtoBuf.ProtoMember(4, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_12.pbDungeonReward> reward
    {
      get { return _reward; }
    }
  
    private int? _state;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state?? default(int); }
      set { _state = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool stateSpecified
    {
      get { return this._state != null; }
      set { if (value == (this._state== null)) this._state = value ? this.state : (int?)null; }
    }
    private bool ShouldSerializestate() { return stateSpecified; }
    private void Resetstate() { stateSpecified = false; }
    
    private int? _score;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score?? default(int); }
      set { _score = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool scoreSpecified
    {
      get { return this._score != null; }
      set { if (value == (this._score== null)) this._score = value ? this.score : (int?)null; }
    }
    private bool ShouldSerializescore() { return scoreSpecified; }
    private void Resetscore() { scoreSpecified = false; }
    
    private int? _left_times;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"left_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int left_times
    {
      get { return _left_times?? default(int); }
      set { _left_times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool left_timesSpecified
    {
      get { return this._left_times != null; }
      set { if (value == (this._left_times== null)) this._left_times = value ? this.left_times : (int?)null; }
    }
    private bool ShouldSerializeleft_times() { return left_timesSpecified; }
    private void Resetleft_times() { left_timesSpecified = false; }
    
    private int? _have_pass_times;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"have_pass_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int have_pass_times
    {
      get { return _have_pass_times?? default(int); }
      set { _have_pass_times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool have_pass_timesSpecified
    {
      get { return this._have_pass_times != null; }
      set { if (value == (this._have_pass_times== null)) this._have_pass_times = value ? this.have_pass_times : (int?)null; }
    }
    private bool ShouldSerializehave_pass_times() { return have_pass_timesSpecified; }
    private void Resethave_pass_times() { have_pass_timesSpecified = false; }
    
    private int? _sub_route;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"sub_route", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sub_route
    {
      get { return _sub_route?? default(int); }
      set { _sub_route = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sub_routeSpecified
    {
      get { return this._sub_route != null; }
      set { if (value == (this._sub_route== null)) this._sub_route = value ? this.sub_route : (int?)null; }
    }
    private bool ShouldSerializesub_route() { return sub_routeSpecified; }
    private void Resetsub_route() { sub_routeSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<int> _condition = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"condition", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> condition
    {
      get { return _condition; }
    }
  
    private int? _challenge_times;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"challenge_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int challenge_times
    {
      get { return _challenge_times?? default(int); }
      set { _challenge_times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool challenge_timesSpecified
    {
      get { return this._challenge_times != null; }
      set { if (value == (this._challenge_times== null)) this._challenge_times = value ? this.challenge_times : (int?)null; }
    }
    private bool ShouldSerializechallenge_times() { return challenge_timesSpecified; }
    private void Resetchallenge_times() { challenge_timesSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<pb_12.pbMugenChallenge> _challenge_list = new global::System.Collections.Generic.List<pb_12.pbMugenChallenge>();
    [global::ProtoBuf.ProtoMember(12, Name=@"challenge_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_12.pbMugenChallenge> challenge_list
    {
      get { return _challenge_list; }
    }
  
    private int? _send_lucky_coin;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"send_lucky_coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int send_lucky_coin
    {
      get { return _send_lucky_coin?? default(int); }
      set { _send_lucky_coin = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool send_lucky_coinSpecified
    {
      get { return this._send_lucky_coin != null; }
      set { if (value == (this._send_lucky_coin== null)) this._send_lucky_coin = value ? this.send_lucky_coin : (int?)null; }
    }
    private bool ShouldSerializesend_lucky_coin() { return send_lucky_coinSpecified; }
    private void Resetsend_lucky_coin() { send_lucky_coinSpecified = false; }
    
    private int? _use_lucky_coin;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"use_lucky_coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int use_lucky_coin
    {
      get { return _use_lucky_coin?? default(int); }
      set { _use_lucky_coin = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool use_lucky_coinSpecified
    {
      get { return this._use_lucky_coin != null; }
      set { if (value == (this._use_lucky_coin== null)) this._use_lucky_coin = value ? this.use_lucky_coin : (int?)null; }
    }
    private bool ShouldSerializeuse_lucky_coin() { return use_lucky_coinSpecified; }
    private void Resetuse_lucky_coin() { use_lucky_coinSpecified = false; }
    
    private int? _max_pass_times;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"max_pass_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int max_pass_times
    {
      get { return _max_pass_times?? default(int); }
      set { _max_pass_times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool max_pass_timesSpecified
    {
      get { return this._max_pass_times != null; }
      set { if (value == (this._max_pass_times== null)) this._max_pass_times = value ? this.max_pass_times : (int?)null; }
    }
    private bool ShouldSerializemax_pass_times() { return max_pass_timesSpecified; }
    private void Resetmax_pass_times() { max_pass_timesSpecified = false; }
    
    private int? _skip_mugen_flag;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"skip_mugen_flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skip_mugen_flag
    {
      get { return _skip_mugen_flag?? default(int); }
      set { _skip_mugen_flag = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool skip_mugen_flagSpecified
    {
      get { return this._skip_mugen_flag != null; }
      set { if (value == (this._skip_mugen_flag== null)) this._skip_mugen_flag = value ? this.skip_mugen_flag : (int?)null; }
    }
    private bool ShouldSerializeskip_mugen_flag() { return skip_mugen_flagSpecified; }
    private void Resetskip_mugen_flag() { skip_mugen_flagSpecified = false; }
    
    private int? _cur_hp;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"cur_hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cur_hp
    {
      get { return _cur_hp?? default(int); }
      set { _cur_hp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool cur_hpSpecified
    {
      get { return this._cur_hp != null; }
      set { if (value == (this._cur_hp== null)) this._cur_hp = value ? this.cur_hp : (int?)null; }
    }
    private bool ShouldSerializecur_hp() { return cur_hpSpecified; }
    private void Resetcur_hp() { cur_hpSpecified = false; }
    
    private int? _buy_times;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"buy_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int buy_times
    {
      get { return _buy_times?? default(int); }
      set { _buy_times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool buy_timesSpecified
    {
      get { return this._buy_times != null; }
      set { if (value == (this._buy_times== null)) this._buy_times = value ? this.buy_times : (int?)null; }
    }
    private bool ShouldSerializebuy_times() { return buy_timesSpecified; }
    private void Resetbuy_times() { buy_timesSpecified = false; }
    
    private int? _ability;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"ability", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ability
    {
      get { return _ability?? default(int); }
      set { _ability = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool abilitySpecified
    {
      get { return this._ability != null; }
      set { if (value == (this._ability== null)) this._ability = value ? this.ability : (int?)null; }
    }
    private bool ShouldSerializeability() { return abilitySpecified; }
    private void Resetability() { abilitySpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbMugenChallenge")]
  public partial class pbMugenChallenge : global::ProtoBuf.IExtensible
  {
    public pbMugenChallenge() {}
    
    private long? _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long player_id
    {
      get { return _player_id?? default(long); }
      set { _player_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool player_idSpecified
    {
      get { return this._player_id != null; }
      set { if (value == (this._player_id== null)) this._player_id = value ? this.player_id : (long?)null; }
    }
    private bool ShouldSerializeplayer_id() { return player_idSpecified; }
    private void Resetplayer_id() { player_idSpecified = false; }
    
    private int? _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level?? default(int); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return this._level != null; }
      set { if (value == (this._level== null)) this._level = value ? this.level : (int?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbChallengeDungeonRank")]
  public partial class pbChallengeDungeonRank : global::ProtoBuf.IExtensible
  {
    public pbChallengeDungeonRank() {}
    
    private readonly global::System.Collections.Generic.List<pb_12.pbChallengeDungeonInfo> _rank_list = new global::System.Collections.Generic.List<pb_12.pbChallengeDungeonInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"rank_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_12.pbChallengeDungeonInfo> rank_list
    {
      get { return _rank_list; }
    }
  
    private int? _self;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"self", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int self
    {
      get { return _self?? default(int); }
      set { _self = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool selfSpecified
    {
      get { return this._self != null; }
      set { if (value == (this._self== null)) this._self = value ? this.self : (int?)null; }
    }
    private bool ShouldSerializeself() { return selfSpecified; }
    private void Resetself() { selfSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbChallengeDungeonInfo")]
  public partial class pbChallengeDungeonInfo : global::ProtoBuf.IExtensible
  {
    public pbChallengeDungeonInfo() {}
    
    private long? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long id
    {
      get { return _id?? default(long); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (long?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name?? ""; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return this._name != null; }
      set { if (value == (this._name== null)) this._name = value ? this.name : (string)null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private int? _lv;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lv
    {
      get { return _lv?? default(int); }
      set { _lv = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lvSpecified
    {
      get { return this._lv != null; }
      set { if (value == (this._lv== null)) this._lv = value ? this.lv : (int?)null; }
    }
    private bool ShouldSerializelv() { return lvSpecified; }
    private void Resetlv() { lvSpecified = false; }
    
    private int? _career;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"career", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int career
    {
      get { return _career?? default(int); }
      set { _career = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool careerSpecified
    {
      get { return this._career != null; }
      set { if (value == (this._career== null)) this._career = value ? this.career : (int?)null; }
    }
    private bool ShouldSerializecareer() { return careerSpecified; }
    private void Resetcareer() { careerSpecified = false; }
    
    private int? _have_pass_times;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"have_pass_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int have_pass_times
    {
      get { return _have_pass_times?? default(int); }
      set { _have_pass_times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool have_pass_timesSpecified
    {
      get { return this._have_pass_times != null; }
      set { if (value == (this._have_pass_times== null)) this._have_pass_times = value ? this.have_pass_times : (int?)null; }
    }
    private bool ShouldSerializehave_pass_times() { return have_pass_timesSpecified; }
    private void Resethave_pass_times() { have_pass_timesSpecified = false; }
    
    private int? _score;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score?? default(int); }
      set { _score = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool scoreSpecified
    {
      get { return this._score != null; }
      set { if (value == (this._score== null)) this._score = value ? this.score : (int?)null; }
    }
    private bool ShouldSerializescore() { return scoreSpecified; }
    private void Resetscore() { scoreSpecified = false; }
    
    private int? _rank;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rank
    {
      get { return _rank?? default(int); }
      set { _rank = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rankSpecified
    {
      get { return this._rank != null; }
      set { if (value == (this._rank== null)) this._rank = value ? this.rank : (int?)null; }
    }
    private bool ShouldSerializerank() { return rankSpecified; }
    private void Resetrank() { rankSpecified = false; }
    
    private int? _battle_ability;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"battle_ability", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int battle_ability
    {
      get { return _battle_ability?? default(int); }
      set { _battle_ability = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool battle_abilitySpecified
    {
      get { return this._battle_ability != null; }
      set { if (value == (this._battle_ability== null)) this._battle_ability = value ? this.battle_ability : (int?)null; }
    }
    private bool ShouldSerializebattle_ability() { return battle_abilitySpecified; }
    private void Resetbattle_ability() { battle_abilitySpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbDungeonSchedule")]
  public partial class pbDungeonSchedule : global::ProtoBuf.IExtensible
  {
    public pbDungeonSchedule() {}
    
    private int? _dungeon_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dungeon_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dungeon_id
    {
      get { return _dungeon_id?? default(int); }
      set { _dungeon_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dungeon_idSpecified
    {
      get { return this._dungeon_id != null; }
      set { if (value == (this._dungeon_id== null)) this._dungeon_id = value ? this.dungeon_id : (int?)null; }
    }
    private bool ShouldSerializedungeon_id() { return dungeon_idSpecified; }
    private void Resetdungeon_id() { dungeon_idSpecified = false; }
    
    private int? _last_dungeon;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"last_dungeon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int last_dungeon
    {
      get { return _last_dungeon?? default(int); }
      set { _last_dungeon = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool last_dungeonSpecified
    {
      get { return this._last_dungeon != null; }
      set { if (value == (this._last_dungeon== null)) this._last_dungeon = value ? this.last_dungeon : (int?)null; }
    }
    private bool ShouldSerializelast_dungeon() { return last_dungeonSpecified; }
    private void Resetlast_dungeon() { last_dungeonSpecified = false; }
    
    private int? _state;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state?? default(int); }
      set { _state = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool stateSpecified
    {
      get { return this._state != null; }
      set { if (value == (this._state== null)) this._state = value ? this.state : (int?)null; }
    }
    private bool ShouldSerializestate() { return stateSpecified; }
    private void Resetstate() { stateSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<pb_12.pbDungeonTarget> _target_info = new global::System.Collections.Generic.List<pb_12.pbDungeonTarget>();
    [global::ProtoBuf.ProtoMember(4, Name=@"target_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_12.pbDungeonTarget> target_info
    {
      get { return _target_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbDungeonTarget")]
  public partial class pbDungeonTarget : global::ProtoBuf.IExtensible
  {
    public pbDungeonTarget() {}
    
    private int? _dungeon_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dungeon_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dungeon_id
    {
      get { return _dungeon_id?? default(int); }
      set { _dungeon_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dungeon_idSpecified
    {
      get { return this._dungeon_id != null; }
      set { if (value == (this._dungeon_id== null)) this._dungeon_id = value ? this.dungeon_id : (int?)null; }
    }
    private bool ShouldSerializedungeon_id() { return dungeon_idSpecified; }
    private void Resetdungeon_id() { dungeon_idSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<int> _target_list = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"target_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> target_list
    {
      get { return _target_list; }
    }
  
    private int? _dungeon_level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"dungeon_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dungeon_level
    {
      get { return _dungeon_level?? default(int); }
      set { _dungeon_level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dungeon_levelSpecified
    {
      get { return this._dungeon_level != null; }
      set { if (value == (this._dungeon_level== null)) this._dungeon_level = value ? this.dungeon_level : (int?)null; }
    }
    private bool ShouldSerializedungeon_level() { return dungeon_levelSpecified; }
    private void Resetdungeon_level() { dungeon_levelSpecified = false; }
    
    private int? _left_times;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"left_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int left_times
    {
      get { return _left_times?? default(int); }
      set { _left_times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool left_timesSpecified
    {
      get { return this._left_times != null; }
      set { if (value == (this._left_times== null)) this._left_times = value ? this.left_times : (int?)null; }
    }
    private bool ShouldSerializeleft_times() { return left_timesSpecified; }
    private void Resetleft_times() { left_timesSpecified = false; }
    
    private int? _buy_times;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"buy_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int buy_times
    {
      get { return _buy_times?? default(int); }
      set { _buy_times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool buy_timesSpecified
    {
      get { return this._buy_times != null; }
      set { if (value == (this._buy_times== null)) this._buy_times = value ? this.buy_times : (int?)null; }
    }
    private bool ShouldSerializebuy_times() { return buy_timesSpecified; }
    private void Resetbuy_times() { buy_timesSpecified = false; }
    
    private int? _best_grade;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"best_grade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int best_grade
    {
      get { return _best_grade?? default(int); }
      set { _best_grade = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool best_gradeSpecified
    {
      get { return this._best_grade != null; }
      set { if (value == (this._best_grade== null)) this._best_grade = value ? this.best_grade : (int?)null; }
    }
    private bool ShouldSerializebest_grade() { return best_gradeSpecified; }
    private void Resetbest_grade() { best_gradeSpecified = false; }
    
    private int? _done;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"done", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int done
    {
      get { return _done?? default(int); }
      set { _done = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool doneSpecified
    {
      get { return this._done != null; }
      set { if (value == (this._done== null)) this._done = value ? this.done : (int?)null; }
    }
    private bool ShouldSerializedone() { return doneSpecified; }
    private void Resetdone() { doneSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbDungeonScheduleList")]
  public partial class pbDungeonScheduleList : global::ProtoBuf.IExtensible
  {
    public pbDungeonScheduleList() {}
    
    private readonly global::System.Collections.Generic.List<pb_12.pbDungeonSchedule> _update_list = new global::System.Collections.Generic.List<pb_12.pbDungeonSchedule>();
    [global::ProtoBuf.ProtoMember(1, Name=@"update_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_12.pbDungeonSchedule> update_list
    {
      get { return _update_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbDailyDungeon")]
  public partial class pbDailyDungeon : global::ProtoBuf.IExtensible
  {
    public pbDailyDungeon() {}
    
    private pb_12.pbDungeon _dungeon = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dungeon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pb_12.pbDungeon dungeon
    {
      get { return _dungeon; }
      set { _dungeon = value; }
    }
    private pb_12.pbDungeonCondition _condition = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"condition", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pb_12.pbDungeonCondition condition
    {
      get { return _condition; }
      set { _condition = value; }
    }
    private int? _pass_flag;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pass_flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pass_flag
    {
      get { return _pass_flag?? default(int); }
      set { _pass_flag = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool pass_flagSpecified
    {
      get { return this._pass_flag != null; }
      set { if (value == (this._pass_flag== null)) this._pass_flag = value ? this.pass_flag : (int?)null; }
    }
    private bool ShouldSerializepass_flag() { return pass_flagSpecified; }
    private void Resetpass_flag() { pass_flagSpecified = false; }
    
    private int? _left_times;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"left_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int left_times
    {
      get { return _left_times?? default(int); }
      set { _left_times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool left_timesSpecified
    {
      get { return this._left_times != null; }
      set { if (value == (this._left_times== null)) this._left_times = value ? this.left_times : (int?)null; }
    }
    private bool ShouldSerializeleft_times() { return left_timesSpecified; }
    private void Resetleft_times() { left_timesSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbSourceDungeon")]
  public partial class pbSourceDungeon : global::ProtoBuf.IExtensible
  {
    public pbSourceDungeon() {}
    
    private readonly global::System.Collections.Generic.List<pb_12.pbSourceDungeonInfo> _info = new global::System.Collections.Generic.List<pb_12.pbSourceDungeonInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_12.pbSourceDungeonInfo> info
    {
      get { return _info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbSourceDungeonInfo")]
  public partial class pbSourceDungeonInfo : global::ProtoBuf.IExtensible
  {
    public pbSourceDungeonInfo() {}
    
    private int? _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type?? default(int); }
      set { _type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return this._type != null; }
      set { if (value == (this._type== null)) this._type = value ? this.type : (int?)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    
    private int? _left_times;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"left_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int left_times
    {
      get { return _left_times?? default(int); }
      set { _left_times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool left_timesSpecified
    {
      get { return this._left_times != null; }
      set { if (value == (this._left_times== null)) this._left_times = value ? this.left_times : (int?)null; }
    }
    private bool ShouldSerializeleft_times() { return left_timesSpecified; }
    private void Resetleft_times() { left_timesSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbDungeonCondition")]
  public partial class pbDungeonCondition : global::ProtoBuf.IExtensible
  {
    public pbDungeonCondition() {}
    
    private int? _time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int time
    {
      get { return _time?? default(int); }
      set { _time = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timeSpecified
    {
      get { return this._time != null; }
      set { if (value == (this._time== null)) this._time = value ? this.time : (int?)null; }
    }
    private bool ShouldSerializetime() { return timeSpecified; }
    private void Resettime() { timeSpecified = false; }
    
    private int? _damage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damage
    {
      get { return _damage?? default(int); }
      set { _damage = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool damageSpecified
    {
      get { return this._damage != null; }
      set { if (value == (this._damage== null)) this._damage = value ? this.damage : (int?)null; }
    }
    private bool ShouldSerializedamage() { return damageSpecified; }
    private void Resetdamage() { damageSpecified = false; }
    
    private int? _hurt;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"hurt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hurt
    {
      get { return _hurt?? default(int); }
      set { _hurt = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool hurtSpecified
    {
      get { return this._hurt != null; }
      set { if (value == (this._hurt== null)) this._hurt = value ? this.hurt : (int?)null; }
    }
    private bool ShouldSerializehurt() { return hurtSpecified; }
    private void Resethurt() { hurtSpecified = false; }
    
    private int? _combo;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"combo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int combo
    {
      get { return _combo?? default(int); }
      set { _combo = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool comboSpecified
    {
      get { return this._combo != null; }
      set { if (value == (this._combo== null)) this._combo = value ? this.combo : (int?)null; }
    }
    private bool ShouldSerializecombo() { return comboSpecified; }
    private void Resetcombo() { comboSpecified = false; }
    
    private int? _aircombo;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"aircombo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int aircombo
    {
      get { return _aircombo?? default(int); }
      set { _aircombo = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool aircomboSpecified
    {
      get { return this._aircombo != null; }
      set { if (value == (this._aircombo== null)) this._aircombo = value ? this.aircombo : (int?)null; }
    }
    private bool ShouldSerializeaircombo() { return aircomboSpecified; }
    private void Resetaircombo() { aircomboSpecified = false; }
    
    private int? _skillcancel;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"skillcancel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillcancel
    {
      get { return _skillcancel?? default(int); }
      set { _skillcancel = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool skillcancelSpecified
    {
      get { return this._skillcancel != null; }
      set { if (value == (this._skillcancel== null)) this._skillcancel = value ? this.skillcancel : (int?)null; }
    }
    private bool ShouldSerializeskillcancel() { return skillcancelSpecified; }
    private void Resetskillcancel() { skillcancelSpecified = false; }
    
    private int? _crit;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"crit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int crit
    {
      get { return _crit?? default(int); }
      set { _crit = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool critSpecified
    {
      get { return this._crit != null; }
      set { if (value == (this._crit== null)) this._crit = value ? this.crit : (int?)null; }
    }
    private bool ShouldSerializecrit() { return critSpecified; }
    private void Resetcrit() { critSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbWinRate")]
  public partial class pbWinRate : global::ProtoBuf.IExtensible
  {
    public pbWinRate() {}
    
    private int? _win_times;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"win_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int win_times
    {
      get { return _win_times?? default(int); }
      set { _win_times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool win_timesSpecified
    {
      get { return this._win_times != null; }
      set { if (value == (this._win_times== null)) this._win_times = value ? this.win_times : (int?)null; }
    }
    private bool ShouldSerializewin_times() { return win_timesSpecified; }
    private void Resetwin_times() { win_timesSpecified = false; }
    
    private int? _fail_times;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"fail_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fail_times
    {
      get { return _fail_times?? default(int); }
      set { _fail_times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool fail_timesSpecified
    {
      get { return this._fail_times != null; }
      set { if (value == (this._fail_times== null)) this._fail_times = value ? this.fail_times : (int?)null; }
    }
    private bool ShouldSerializefail_times() { return fail_timesSpecified; }
    private void Resetfail_times() { fail_timesSpecified = false; }
    
    private int? _win_rate;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"win_rate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int win_rate
    {
      get { return _win_rate?? default(int); }
      set { _win_rate = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool win_rateSpecified
    {
      get { return this._win_rate != null; }
      set { if (value == (this._win_rate== null)) this._win_rate = value ? this.win_rate : (int?)null; }
    }
    private bool ShouldSerializewin_rate() { return win_rateSpecified; }
    private void Resetwin_rate() { win_rateSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbMopUpList")]
  public partial class pbMopUpList : global::ProtoBuf.IExtensible
  {
    public pbMopUpList() {}
    
    private int? _dungeon_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dungeon_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dungeon_id
    {
      get { return _dungeon_id?? default(int); }
      set { _dungeon_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dungeon_idSpecified
    {
      get { return this._dungeon_id != null; }
      set { if (value == (this._dungeon_id== null)) this._dungeon_id = value ? this.dungeon_id : (int?)null; }
    }
    private bool ShouldSerializedungeon_id() { return dungeon_idSpecified; }
    private void Resetdungeon_id() { dungeon_idSpecified = false; }
    
    private int? _times;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int times
    {
      get { return _times?? default(int); }
      set { _times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timesSpecified
    {
      get { return this._times != null; }
      set { if (value == (this._times== null)) this._times = value ? this.times : (int?)null; }
    }
    private bool ShouldSerializetimes() { return timesSpecified; }
    private void Resettimes() { timesSpecified = false; }
    
    private int? _flip_pay_card;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"flip_pay_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int flip_pay_card
    {
      get { return _flip_pay_card?? default(int); }
      set { _flip_pay_card = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool flip_pay_cardSpecified
    {
      get { return this._flip_pay_card != null; }
      set { if (value == (this._flip_pay_card== null)) this._flip_pay_card = value ? this.flip_pay_card : (int?)null; }
    }
    private bool ShouldSerializeflip_pay_card() { return flip_pay_cardSpecified; }
    private void Resetflip_pay_card() { flip_pay_cardSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<pb_12.pbMopUp> _mop_up_info = new global::System.Collections.Generic.List<pb_12.pbMopUp>();
    [global::ProtoBuf.ProtoMember(4, Name=@"mop_up_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_12.pbMopUp> mop_up_info
    {
      get { return _mop_up_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbMopUp")]
  public partial class pbMopUp : global::ProtoBuf.IExtensible
  {
    public pbMopUp() {}
    
    private readonly global::System.Collections.Generic.List<pb_12.pbDungeonReward> _normal_reward = new global::System.Collections.Generic.List<pb_12.pbDungeonReward>();
    [global::ProtoBuf.ProtoMember(1, Name=@"normal_reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_12.pbDungeonReward> normal_reward
    {
      get { return _normal_reward; }
    }
  
    private readonly global::System.Collections.Generic.List<pb_12.pbDungeonReward> _boss_reward = new global::System.Collections.Generic.List<pb_12.pbDungeonReward>();
    [global::ProtoBuf.ProtoMember(2, Name=@"boss_reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_12.pbDungeonReward> boss_reward
    {
      get { return _boss_reward; }
    }
  
    private readonly global::System.Collections.Generic.List<pb_12.pbDungeonReward> _free_card_reward = new global::System.Collections.Generic.List<pb_12.pbDungeonReward>();
    [global::ProtoBuf.ProtoMember(3, Name=@"free_card_reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_12.pbDungeonReward> free_card_reward
    {
      get { return _free_card_reward; }
    }
  
    private readonly global::System.Collections.Generic.List<pb_12.pbDungeonReward> _pay_card_reward = new global::System.Collections.Generic.List<pb_12.pbDungeonReward>();
    [global::ProtoBuf.ProtoMember(4, Name=@"pay_card_reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_12.pbDungeonReward> pay_card_reward
    {
      get { return _pay_card_reward; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}