//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: pb_16.proto
// Note: requires additional types generated from: pb_common.proto
namespace pb_16
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbFashion")]
  public partial class pbFashion : global::ProtoBuf.IExtensible
  {
    public pbFashion() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private int? _nid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nid
    {
      get { return _nid?? default(int); }
      set { _nid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nidSpecified
    {
      get { return this._nid != null; }
      set { if (value == (this._nid== null)) this._nid = value ? this.nid : (int?)null; }
    }
    private bool ShouldSerializenid() { return nidSpecified; }
    private void Resetnid() { nidSpecified = false; }
    
    private int? _base_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"base_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int base_id
    {
      get { return _base_id?? default(int); }
      set { _base_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool base_idSpecified
    {
      get { return this._base_id != null; }
      set { if (value == (this._base_id== null)) this._base_id = value ? this.base_id : (int?)null; }
    }
    private bool ShouldSerializebase_id() { return base_idSpecified; }
    private void Resetbase_id() { base_idSpecified = false; }
    
    private int? _container;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"container", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int container
    {
      get { return _container?? default(int); }
      set { _container = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool containerSpecified
    {
      get { return this._container != null; }
      set { if (value == (this._container== null)) this._container = value ? this.container : (int?)null; }
    }
    private bool ShouldSerializecontainer() { return containerSpecified; }
    private void Resetcontainer() { containerSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbFashionList")]
  public partial class pbFashionList : global::ProtoBuf.IExtensible
  {
    public pbFashionList() {}
    
    private int? _current_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"current_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int current_id
    {
      get { return _current_id?? default(int); }
      set { _current_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool current_idSpecified
    {
      get { return this._current_id != null; }
      set { if (value == (this._current_id== null)) this._current_id = value ? this.current_id : (int?)null; }
    }
    private bool ShouldSerializecurrent_id() { return current_idSpecified; }
    private void Resetcurrent_id() { current_idSpecified = false; }
    
    private int? _change_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"change_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int change_id
    {
      get { return _change_id?? default(int); }
      set { _change_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool change_idSpecified
    {
      get { return this._change_id != null; }
      set { if (value == (this._change_id== null)) this._change_id = value ? this.change_id : (int?)null; }
    }
    private bool ShouldSerializechange_id() { return change_idSpecified; }
    private void Resetchange_id() { change_idSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<pb_16.pbFashion> _fashion_list = new global::System.Collections.Generic.List<pb_16.pbFashion>();
    [global::ProtoBuf.ProtoMember(3, Name=@"fashion_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_16.pbFashion> fashion_list
    {
      get { return _fashion_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}