//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: pb_14.proto
// Note: requires additional types generated from: pb_common.proto
namespace pb_14
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbFriendList")]
  public partial class pbFriendList : global::ProtoBuf.IExtensible
  {
    public pbFriendList() {}
    
    private readonly global::System.Collections.Generic.List<pb_common.pbFriend> _update_list = new global::System.Collections.Generic.List<pb_common.pbFriend>();
    [global::ProtoBuf.ProtoMember(1, Name=@"update_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_common.pbFriend> update_list
    {
      get { return _update_list; }
    }
  
    private readonly global::System.Collections.Generic.List<pb_common.pbFriend> _delete_list = new global::System.Collections.Generic.List<pb_common.pbFriend>();
    [global::ProtoBuf.ProtoMember(2, Name=@"delete_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_common.pbFriend> delete_list
    {
      get { return _delete_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}