//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: pb_10.proto
// Note: requires additional types generated from: pb_common.proto
namespace pb_10
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbAccount")]
  public partial class pbAccount : global::ProtoBuf.IExtensible
  {
    public pbAccount() {}
    
    private long? _acc_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long acc_id
    {
      get { return _acc_id?? default(long); }
      set { _acc_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool acc_idSpecified
    {
      get { return this._acc_id != null; }
      set { if (value == (this._acc_id== null)) this._acc_id = value ? this.acc_id : (long?)null; }
    }
    private bool ShouldSerializeacc_id() { return acc_idSpecified; }
    private void Resetacc_id() { acc_idSpecified = false; }
    
    private string _acc_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"acc_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string acc_name
    {
      get { return _acc_name?? ""; }
      set { _acc_name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool acc_nameSpecified
    {
      get { return this._acc_name != null; }
      set { if (value == (this._acc_name== null)) this._acc_name = value ? this.acc_name : (string)null; }
    }
    private bool ShouldSerializeacc_name() { return acc_nameSpecified; }
    private void Resetacc_name() { acc_nameSpecified = false; }
    
    private int? _timestamp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timestamp
    {
      get { return _timestamp?? default(int); }
      set { _timestamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timestampSpecified
    {
      get { return this._timestamp != null; }
      set { if (value == (this._timestamp== null)) this._timestamp = value ? this.timestamp : (int?)null; }
    }
    private bool ShouldSerializetimestamp() { return timestampSpecified; }
    private void Resettimestamp() { timestampSpecified = false; }
    
    private int? _server_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"server_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int server_id
    {
      get { return _server_id?? default(int); }
      set { _server_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool server_idSpecified
    {
      get { return this._server_id != null; }
      set { if (value == (this._server_id== null)) this._server_id = value ? this.server_id : (int?)null; }
    }
    private bool ShouldSerializeserver_id() { return server_idSpecified; }
    private void Resetserver_id() { server_idSpecified = false; }
    
    private string _login_ticket;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"login_ticket", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string login_ticket
    {
      get { return _login_ticket?? ""; }
      set { _login_ticket = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool login_ticketSpecified
    {
      get { return this._login_ticket != null; }
      set { if (value == (this._login_ticket== null)) this._login_ticket = value ? this.login_ticket : (string)null; }
    }
    private bool ShouldSerializelogin_ticket() { return login_ticketSpecified; }
    private void Resetlogin_ticket() { login_ticketSpecified = false; }
    
    private string _suid;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"suid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string suid
    {
      get { return _suid?? ""; }
      set { _suid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool suidSpecified
    {
      get { return this._suid != null; }
      set { if (value == (this._suid== null)) this._suid = value ? this.suid : (string)null; }
    }
    private bool ShouldSerializesuid() { return suidSpecified; }
    private void Resetsuid() { suidSpecified = false; }
    
    private string _platform;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"platform", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string platform
    {
      get { return _platform?? ""; }
      set { _platform = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool platformSpecified
    {
      get { return this._platform != null; }
      set { if (value == (this._platform== null)) this._platform = value ? this.platform : (string)null; }
    }
    private bool ShouldSerializeplatform() { return platformSpecified; }
    private void Resetplatform() { platformSpecified = false; }
    
    private string _device_id;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"device_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string device_id
    {
      get { return _device_id?? ""; }
      set { _device_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool device_idSpecified
    {
      get { return this._device_id != null; }
      set { if (value == (this._device_id== null)) this._device_id = value ? this.device_id : (string)null; }
    }
    private bool ShouldSerializedevice_id() { return device_idSpecified; }
    private void Resetdevice_id() { device_idSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbUserLoginInfo")]
  public partial class pbUserLoginInfo : global::ProtoBuf.IExtensible
  {
    public pbUserLoginInfo() {}
    
    private long? _user_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long user_id
    {
      get { return _user_id?? default(long); }
      set { _user_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool user_idSpecified
    {
      get { return this._user_id != null; }
      set { if (value == (this._user_id== null)) this._user_id = value ? this.user_id : (long?)null; }
    }
    private bool ShouldSerializeuser_id() { return user_idSpecified; }
    private void Resetuser_id() { user_idSpecified = false; }
    
    private string _nickname;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickname
    {
      get { return _nickname?? ""; }
      set { _nickname = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nicknameSpecified
    {
      get { return this._nickname != null; }
      set { if (value == (this._nickname== null)) this._nickname = value ? this.nickname : (string)null; }
    }
    private bool ShouldSerializenickname() { return nicknameSpecified; }
    private void Resetnickname() { nicknameSpecified = false; }
    
    private int? _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level?? default(int); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return this._level != null; }
      set { if (value == (this._level== null)) this._level = value ? this.level : (int?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    
    private int? _camp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int camp
    {
      get { return _camp?? default(int); }
      set { _camp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool campSpecified
    {
      get { return this._camp != null; }
      set { if (value == (this._camp== null)) this._camp = value ? this.camp : (int?)null; }
    }
    private bool ShouldSerializecamp() { return campSpecified; }
    private void Resetcamp() { campSpecified = false; }
    
    private int? _career;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"career", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int career
    {
      get { return _career?? default(int); }
      set { _career = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool careerSpecified
    {
      get { return this._career != null; }
      set { if (value == (this._career== null)) this._career = value ? this.career : (int?)null; }
    }
    private bool ShouldSerializecareer() { return careerSpecified; }
    private void Resetcareer() { careerSpecified = false; }
    
    private int? _sex;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex?? default(int); }
      set { _sex = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sexSpecified
    {
      get { return this._sex != null; }
      set { if (value == (this._sex== null)) this._sex = value ? this.sex : (int?)null; }
    }
    private bool ShouldSerializesex() { return sexSpecified; }
    private void Resetsex() { sexSpecified = false; }
    
    private int? _server_id;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"server_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int server_id
    {
      get { return _server_id?? default(int); }
      set { _server_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool server_idSpecified
    {
      get { return this._server_id != null; }
      set { if (value == (this._server_id== null)) this._server_id = value ? this.server_id : (int?)null; }
    }
    private bool ShouldSerializeserver_id() { return server_idSpecified; }
    private void Resetserver_id() { server_idSpecified = false; }
    
    private int? _status;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status?? default(int); }
      set { _status = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool statusSpecified
    {
      get { return this._status != null; }
      set { if (value == (this._status== null)) this._status = value ? this.status : (int?)null; }
    }
    private bool ShouldSerializestatus() { return statusSpecified; }
    private void Resetstatus() { statusSpecified = false; }
    
    private string _acc_id;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string acc_id
    {
      get { return _acc_id?? ""; }
      set { _acc_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool acc_idSpecified
    {
      get { return this._acc_id != null; }
      set { if (value == (this._acc_id== null)) this._acc_id = value ? this.acc_id : (string)null; }
    }
    private bool ShouldSerializeacc_id() { return acc_idSpecified; }
    private void Resetacc_id() { acc_idSpecified = false; }
    
    private string _acc_name;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"acc_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string acc_name
    {
      get { return _acc_name?? ""; }
      set { _acc_name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool acc_nameSpecified
    {
      get { return this._acc_name != null; }
      set { if (value == (this._acc_name== null)) this._acc_name = value ? this.acc_name : (string)null; }
    }
    private bool ShouldSerializeacc_name() { return acc_nameSpecified; }
    private void Resetacc_name() { acc_nameSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbAccountLogin")]
  public partial class pbAccountLogin : global::ProtoBuf.IExtensible
  {
    public pbAccountLogin() {}
    
    private int? _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result?? default(int); }
      set { _result = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool resultSpecified
    {
      get { return this._result != null; }
      set { if (value == (this._result== null)) this._result = value ? this.result : (int?)null; }
    }
    private bool ShouldSerializeresult() { return resultSpecified; }
    private void Resetresult() { resultSpecified = false; }
    
    private int? _total_online;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"total_online", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int total_online
    {
      get { return _total_online?? default(int); }
      set { _total_online = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool total_onlineSpecified
    {
      get { return this._total_online != null; }
      set { if (value == (this._total_online== null)) this._total_online = value ? this.total_online : (int?)null; }
    }
    private bool ShouldSerializetotal_online() { return total_onlineSpecified; }
    private void Resettotal_online() { total_onlineSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<pb_10.pbUserLoginInfo> _user_info = new global::System.Collections.Generic.List<pb_10.pbUserLoginInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"user_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_10.pbUserLoginInfo> user_info
    {
      get { return _user_info; }
    }
  
    private string _acc_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string acc_id
    {
      get { return _acc_id?? ""; }
      set { _acc_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool acc_idSpecified
    {
      get { return this._acc_id != null; }
      set { if (value == (this._acc_id== null)) this._acc_id = value ? this.acc_id : (string)null; }
    }
    private bool ShouldSerializeacc_id() { return acc_idSpecified; }
    private void Resetacc_id() { acc_idSpecified = false; }
    
    private int? _session;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int session
    {
      get { return _session?? default(int); }
      set { _session = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sessionSpecified
    {
      get { return this._session != null; }
      set { if (value == (this._session== null)) this._session = value ? this.session : (int?)null; }
    }
    private bool ShouldSerializesession() { return sessionSpecified; }
    private void Resetsession() { sessionSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbCreateARole")]
  public partial class pbCreateARole : global::ProtoBuf.IExtensible
  {
    public pbCreateARole() {}
    
    private int? _server_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"server_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int server_id
    {
      get { return _server_id?? default(int); }
      set { _server_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool server_idSpecified
    {
      get { return this._server_id != null; }
      set { if (value == (this._server_id== null)) this._server_id = value ? this.server_id : (int?)null; }
    }
    private bool ShouldSerializeserver_id() { return server_idSpecified; }
    private void Resetserver_id() { server_idSpecified = false; }
    
    private long? _acc_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"acc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long acc_id
    {
      get { return _acc_id?? default(long); }
      set { _acc_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool acc_idSpecified
    {
      get { return this._acc_id != null; }
      set { if (value == (this._acc_id== null)) this._acc_id = value ? this.acc_id : (long?)null; }
    }
    private bool ShouldSerializeacc_id() { return acc_idSpecified; }
    private void Resetacc_id() { acc_idSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbServerStatus")]
  public partial class pbServerStatus : global::ProtoBuf.IExtensible
  {
    public pbServerStatus() {}
    
    private int? _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index?? default(int); }
      set { _index = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool indexSpecified
    {
      get { return this._index != null; }
      set { if (value == (this._index== null)) this._index = value ? this.index : (int?)null; }
    }
    private bool ShouldSerializeindex() { return indexSpecified; }
    private void Resetindex() { indexSpecified = false; }
    
    private string _ip;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ip
    {
      get { return _ip?? ""; }
      set { _ip = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ipSpecified
    {
      get { return this._ip != null; }
      set { if (value == (this._ip== null)) this._ip = value ? this.ip : (string)null; }
    }
    private bool ShouldSerializeip() { return ipSpecified; }
    private void Resetip() { ipSpecified = false; }
    
    private int? _port;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int port
    {
      get { return _port?? default(int); }
      set { _port = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool portSpecified
    {
      get { return this._port != null; }
      set { if (value == (this._port== null)) this._port = value ? this.port : (int?)null; }
    }
    private bool ShouldSerializeport() { return portSpecified; }
    private void Resetport() { portSpecified = false; }
    
    private int? _state;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state?? default(int); }
      set { _state = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool stateSpecified
    {
      get { return this._state != null; }
      set { if (value == (this._state== null)) this._state = value ? this.state : (int?)null; }
    }
    private bool ShouldSerializestate() { return stateSpecified; }
    private void Resetstate() { stateSpecified = false; }
    
    private int? _num;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num?? default(int); }
      set { _num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numSpecified
    {
      get { return this._num != null; }
      set { if (value == (this._num== null)) this._num = value ? this.num : (int?)null; }
    }
    private bool ShouldSerializenum() { return numSpecified; }
    private void Resetnum() { numSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbUserResult")]
  public partial class pbUserResult : global::ProtoBuf.IExtensible
  {
    public pbUserResult() {}
    
    private int? _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result?? default(int); }
      set { _result = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool resultSpecified
    {
      get { return this._result != null; }
      set { if (value == (this._result== null)) this._result = value ? this.result : (int?)null; }
    }
    private bool ShouldSerializeresult() { return resultSpecified; }
    private void Resetresult() { resultSpecified = false; }
    
    private long? _user_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long user_id
    {
      get { return _user_id?? default(long); }
      set { _user_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool user_idSpecified
    {
      get { return this._user_id != null; }
      set { if (value == (this._user_id== null)) this._user_id = value ? this.user_id : (long?)null; }
    }
    private bool ShouldSerializeuser_id() { return user_idSpecified; }
    private void Resetuser_id() { user_idSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}