//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: pb_17.proto
// Note: requires additional types generated from: pb_common.proto
namespace pb_17
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbBossList")]
  public partial class pbBossList : global::ProtoBuf.IExtensible
  {
    public pbBossList() {}
    
    private readonly global::System.Collections.Generic.List<pb_17.pbWorldBoss> _update_list = new global::System.Collections.Generic.List<pb_17.pbWorldBoss>();
    [global::ProtoBuf.ProtoMember(1, Name=@"update_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_17.pbWorldBoss> update_list
    {
      get { return _update_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbWorldBoss")]
  public partial class pbWorldBoss : global::ProtoBuf.IExtensible
  {
    public pbWorldBoss() {}
    
    private int? _boss_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"boss_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int boss_id
    {
      get { return _boss_id?? default(int); }
      set { _boss_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool boss_idSpecified
    {
      get { return this._boss_id != null; }
      set { if (value == (this._boss_id== null)) this._boss_id = value ? this.boss_id : (int?)null; }
    }
    private bool ShouldSerializeboss_id() { return boss_idSpecified; }
    private void Resetboss_id() { boss_idSpecified = false; }
    
    private int? _hp_cur;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"hp_cur", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp_cur
    {
      get { return _hp_cur?? default(int); }
      set { _hp_cur = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool hp_curSpecified
    {
      get { return this._hp_cur != null; }
      set { if (value == (this._hp_cur== null)) this._hp_cur = value ? this.hp_cur : (int?)null; }
    }
    private bool ShouldSerializehp_cur() { return hp_curSpecified; }
    private void Resethp_cur() { hp_curSpecified = false; }
    
    private long? _player_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long player_id
    {
      get { return _player_id?? default(long); }
      set { _player_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool player_idSpecified
    {
      get { return this._player_id != null; }
      set { if (value == (this._player_id== null)) this._player_id = value ? this.player_id : (long?)null; }
    }
    private bool ShouldSerializeplayer_id() { return player_idSpecified; }
    private void Resetplayer_id() { player_idSpecified = false; }
    
    private string _nickname;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickname
    {
      get { return _nickname?? ""; }
      set { _nickname = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nicknameSpecified
    {
      get { return this._nickname != null; }
      set { if (value == (this._nickname== null)) this._nickname = value ? this.nickname : (string)null; }
    }
    private bool ShouldSerializenickname() { return nicknameSpecified; }
    private void Resetnickname() { nicknameSpecified = false; }
    
    private int? _start;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"start", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int start
    {
      get { return _start?? default(int); }
      set { _start = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool startSpecified
    {
      get { return this._start != null; }
      set { if (value == (this._start== null)) this._start = value ? this.start : (int?)null; }
    }
    private bool ShouldSerializestart() { return startSpecified; }
    private void Resetstart() { startSpecified = false; }
    
    private int? _stop;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"stop", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stop
    {
      get { return _stop?? default(int); }
      set { _stop = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool stopSpecified
    {
      get { return this._stop != null; }
      set { if (value == (this._stop== null)) this._stop = value ? this.stop : (int?)null; }
    }
    private bool ShouldSerializestop() { return stopSpecified; }
    private void Resetstop() { stopSpecified = false; }
    
    private int? _count;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count?? default(int); }
      set { _count = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool countSpecified
    {
      get { return this._count != null; }
      set { if (value == (this._count== null)) this._count = value ? this.count : (int?)null; }
    }
    private bool ShouldSerializecount() { return countSpecified; }
    private void Resetcount() { countSpecified = false; }
    
    private int? _damage;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damage
    {
      get { return _damage?? default(int); }
      set { _damage = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool damageSpecified
    {
      get { return this._damage != null; }
      set { if (value == (this._damage== null)) this._damage = value ? this.damage : (int?)null; }
    }
    private bool ShouldSerializedamage() { return damageSpecified; }
    private void Resetdamage() { damageSpecified = false; }
    
    private int? _rank;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rank
    {
      get { return _rank?? default(int); }
      set { _rank = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rankSpecified
    {
      get { return this._rank != null; }
      set { if (value == (this._rank== null)) this._rank = value ? this.rank : (int?)null; }
    }
    private bool ShouldSerializerank() { return rankSpecified; }
    private void Resetrank() { rankSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<pb_17.pbCritMsg> _msg = new global::System.Collections.Generic.List<pb_17.pbCritMsg>();
    [global::ProtoBuf.ProtoMember(10, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_17.pbCritMsg> msg
    {
      get { return _msg; }
    }
  
    private readonly global::System.Collections.Generic.List<pb_17.pbRank> _rank_info = new global::System.Collections.Generic.List<pb_17.pbRank>();
    [global::ProtoBuf.ProtoMember(11, Name=@"rank_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_17.pbRank> rank_info
    {
      get { return _rank_info; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _crit_damage = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(12, Name=@"crit_damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> crit_damage
    {
      get { return _crit_damage; }
    }
  
    private int? _state;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state?? default(int); }
      set { _state = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool stateSpecified
    {
      get { return this._state != null; }
      set { if (value == (this._state== null)) this._state = value ? this.state : (int?)null; }
    }
    private bool ShouldSerializestate() { return stateSpecified; }
    private void Resetstate() { stateSpecified = false; }
    
    private int? _boss_lv;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"boss_lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int boss_lv
    {
      get { return _boss_lv?? default(int); }
      set { _boss_lv = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool boss_lvSpecified
    {
      get { return this._boss_lv != null; }
      set { if (value == (this._boss_lv== null)) this._boss_lv = value ? this.boss_lv : (int?)null; }
    }
    private bool ShouldSerializeboss_lv() { return boss_lvSpecified; }
    private void Resetboss_lv() { boss_lvSpecified = false; }
    
    private int? _hp_lim;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"hp_lim", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp_lim
    {
      get { return _hp_lim?? default(int); }
      set { _hp_lim = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool hp_limSpecified
    {
      get { return this._hp_lim != null; }
      set { if (value == (this._hp_lim== null)) this._hp_lim = value ? this.hp_lim : (int?)null; }
    }
    private bool ShouldSerializehp_lim() { return hp_limSpecified; }
    private void Resethp_lim() { hp_limSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbRank")]
  public partial class pbRank : global::ProtoBuf.IExtensible
  {
    public pbRank() {}
    
    private string _nickname;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickname
    {
      get { return _nickname?? ""; }
      set { _nickname = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nicknameSpecified
    {
      get { return this._nickname != null; }
      set { if (value == (this._nickname== null)) this._nickname = value ? this.nickname : (string)null; }
    }
    private bool ShouldSerializenickname() { return nicknameSpecified; }
    private void Resetnickname() { nicknameSpecified = false; }
    
    private int? _damage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damage
    {
      get { return _damage?? default(int); }
      set { _damage = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool damageSpecified
    {
      get { return this._damage != null; }
      set { if (value == (this._damage== null)) this._damage = value ? this.damage : (int?)null; }
    }
    private bool ShouldSerializedamage() { return damageSpecified; }
    private void Resetdamage() { damageSpecified = false; }
    
    private int? _career;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"career", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int career
    {
      get { return _career?? default(int); }
      set { _career = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool careerSpecified
    {
      get { return this._career != null; }
      set { if (value == (this._career== null)) this._career = value ? this.career : (int?)null; }
    }
    private bool ShouldSerializecareer() { return careerSpecified; }
    private void Resetcareer() { careerSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbCritMsg")]
  public partial class pbCritMsg : global::ProtoBuf.IExtensible
  {
    public pbCritMsg() {}
    
    private string _nickname;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickname
    {
      get { return _nickname?? ""; }
      set { _nickname = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nicknameSpecified
    {
      get { return this._nickname != null; }
      set { if (value == (this._nickname== null)) this._nickname = value ? this.nickname : (string)null; }
    }
    private bool ShouldSerializenickname() { return nicknameSpecified; }
    private void Resetnickname() { nicknameSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<int> _crit_damage = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"crit_damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> crit_damage
    {
      get { return _crit_damage; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}