//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: pb_24.proto
namespace pb_24
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbRankInfo")]
  public partial class pbRankInfo : global::ProtoBuf.IExtensible
  {
    public pbRankInfo() {}
    
    private long? _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long player_id
    {
      get { return _player_id?? default(long); }
      set { _player_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool player_idSpecified
    {
      get { return this._player_id != null; }
      set { if (value == (this._player_id== null)) this._player_id = value ? this.player_id : (long?)null; }
    }
    private bool ShouldSerializeplayer_id() { return player_idSpecified; }
    private void Resetplayer_id() { player_idSpecified = false; }
    
    private int? _career;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"career", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int career
    {
      get { return _career?? default(int); }
      set { _career = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool careerSpecified
    {
      get { return this._career != null; }
      set { if (value == (this._career== null)) this._career = value ? this.career : (int?)null; }
    }
    private bool ShouldSerializecareer() { return careerSpecified; }
    private void Resetcareer() { careerSpecified = false; }
    
    private string _nickname;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickname
    {
      get { return _nickname?? ""; }
      set { _nickname = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nicknameSpecified
    {
      get { return this._nickname != null; }
      set { if (value == (this._nickname== null)) this._nickname = value ? this.nickname : (string)null; }
    }
    private bool ShouldSerializenickname() { return nicknameSpecified; }
    private void Resetnickname() { nicknameSpecified = false; }
    
    private int? _level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level?? default(int); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return this._level != null; }
      set { if (value == (this._level== null)) this._level = value ? this.level : (int?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    
    private int? _rank;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rank
    {
      get { return _rank?? default(int); }
      set { _rank = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rankSpecified
    {
      get { return this._rank != null; }
      set { if (value == (this._rank== null)) this._rank = value ? this.rank : (int?)null; }
    }
    private bool ShouldSerializerank() { return rankSpecified; }
    private void Resetrank() { rankSpecified = false; }
    
    private int? _value;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int value
    {
      get { return _value?? default(int); }
      set { _value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool valueSpecified
    {
      get { return this._value != null; }
      set { if (value == (this._value== null)) this._value = value ? this.value : (int?)null; }
    }
    private bool ShouldSerializevalue() { return valueSpecified; }
    private void Resetvalue() { valueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbRankList")]
  public partial class pbRankList : global::ProtoBuf.IExtensible
  {
    public pbRankList() {}
    
    private readonly global::System.Collections.Generic.List<pb_24.pbRankInfo> _rank_list = new global::System.Collections.Generic.List<pb_24.pbRankInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"rank_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_24.pbRankInfo> rank_list
    {
      get { return _rank_list; }
    }
  
    private int? _rank;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rank
    {
      get { return _rank?? default(int); }
      set { _rank = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rankSpecified
    {
      get { return this._rank != null; }
      set { if (value == (this._rank== null)) this._rank = value ? this.rank : (int?)null; }
    }
    private bool ShouldSerializerank() { return rankSpecified; }
    private void Resetrank() { rankSpecified = false; }
    
    private int? _value;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int value
    {
      get { return _value?? default(int); }
      set { _value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool valueSpecified
    {
      get { return this._value != null; }
      set { if (value == (this._value== null)) this._value = value ? this.value : (int?)null; }
    }
    private bool ShouldSerializevalue() { return valueSpecified; }
    private void Resetvalue() { valueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}