//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: pb_23.proto
// Note: requires additional types generated from: pb_common.proto
namespace pb_23
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbArenaInfo")]
  public partial class pbArenaInfo : global::ProtoBuf.IExtensible
  {
    public pbArenaInfo() {}
    
    private int? _challenge_times;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"challenge_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int challenge_times
    {
      get { return _challenge_times?? default(int); }
      set { _challenge_times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool challenge_timesSpecified
    {
      get { return this._challenge_times != null; }
      set { if (value == (this._challenge_times== null)) this._challenge_times = value ? this.challenge_times : (int?)null; }
    }
    private bool ShouldSerializechallenge_times() { return challenge_timesSpecified; }
    private void Resetchallenge_times() { challenge_timesSpecified = false; }
    
    private int? _rest_challenge_times;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rest_challenge_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rest_challenge_times
    {
      get { return _rest_challenge_times?? default(int); }
      set { _rest_challenge_times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rest_challenge_timesSpecified
    {
      get { return this._rest_challenge_times != null; }
      set { if (value == (this._rest_challenge_times== null)) this._rest_challenge_times = value ? this.rest_challenge_times : (int?)null; }
    }
    private bool ShouldSerializerest_challenge_times() { return rest_challenge_timesSpecified; }
    private void Resetrest_challenge_times() { rest_challenge_timesSpecified = false; }
    
    private int? _challenge_timestamp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"challenge_timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int challenge_timestamp
    {
      get { return _challenge_timestamp?? default(int); }
      set { _challenge_timestamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool challenge_timestampSpecified
    {
      get { return this._challenge_timestamp != null; }
      set { if (value == (this._challenge_timestamp== null)) this._challenge_timestamp = value ? this.challenge_timestamp : (int?)null; }
    }
    private bool ShouldSerializechallenge_timestamp() { return challenge_timestampSpecified; }
    private void Resetchallenge_timestamp() { challenge_timestampSpecified = false; }
    
    private int? _rank;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rank
    {
      get { return _rank?? default(int); }
      set { _rank = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rankSpecified
    {
      get { return this._rank != null; }
      set { if (value == (this._rank== null)) this._rank = value ? this.rank : (int?)null; }
    }
    private bool ShouldSerializerank() { return rankSpecified; }
    private void Resetrank() { rankSpecified = false; }
    
    private int? _win_times;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"win_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int win_times
    {
      get { return _win_times?? default(int); }
      set { _win_times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool win_timesSpecified
    {
      get { return this._win_times != null; }
      set { if (value == (this._win_times== null)) this._win_times = value ? this.win_times : (int?)null; }
    }
    private bool ShouldSerializewin_times() { return win_timesSpecified; }
    private void Resetwin_times() { win_timesSpecified = false; }
    
    private int? _fail_times;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"fail_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fail_times
    {
      get { return _fail_times?? default(int); }
      set { _fail_times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool fail_timesSpecified
    {
      get { return this._fail_times != null; }
      set { if (value == (this._fail_times== null)) this._fail_times = value ? this.fail_times : (int?)null; }
    }
    private bool ShouldSerializefail_times() { return fail_timesSpecified; }
    private void Resetfail_times() { fail_timesSpecified = false; }
    
    private int? _robot;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"robot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int robot
    {
      get { return _robot?? default(int); }
      set { _robot = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool robotSpecified
    {
      get { return this._robot != null; }
      set { if (value == (this._robot== null)) this._robot = value ? this.robot : (int?)null; }
    }
    private bool ShouldSerializerobot() { return robotSpecified; }
    private void Resetrobot() { robotSpecified = false; }
    
    private long? _player_id;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long player_id
    {
      get { return _player_id?? default(long); }
      set { _player_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool player_idSpecified
    {
      get { return this._player_id != null; }
      set { if (value == (this._player_id== null)) this._player_id = value ? this.player_id : (long?)null; }
    }
    private bool ShouldSerializeplayer_id() { return player_idSpecified; }
    private void Resetplayer_id() { player_idSpecified = false; }
    
    private int? _level;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level?? default(int); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return this._level != null; }
      set { if (value == (this._level== null)) this._level = value ? this.level : (int?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    
    private string _nickname;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickname
    {
      get { return _nickname?? ""; }
      set { _nickname = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nicknameSpecified
    {
      get { return this._nickname != null; }
      set { if (value == (this._nickname== null)) this._nickname = value ? this.nickname : (string)null; }
    }
    private bool ShouldSerializenickname() { return nicknameSpecified; }
    private void Resetnickname() { nicknameSpecified = false; }
    
    private int? _career;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"career", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int career
    {
      get { return _career?? default(int); }
      set { _career = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool careerSpecified
    {
      get { return this._career != null; }
      set { if (value == (this._career== null)) this._career = value ? this.career : (int?)null; }
    }
    private bool ShouldSerializecareer() { return careerSpecified; }
    private void Resetcareer() { careerSpecified = false; }
    
    private int? _battle_ability;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"battle_ability", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int battle_ability
    {
      get { return _battle_ability?? default(int); }
      set { _battle_ability = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool battle_abilitySpecified
    {
      get { return this._battle_ability != null; }
      set { if (value == (this._battle_ability== null)) this._battle_ability = value ? this.battle_ability : (int?)null; }
    }
    private bool ShouldSerializebattle_ability() { return battle_abilitySpecified; }
    private void Resetbattle_ability() { battle_abilitySpecified = false; }
    
    private readonly global::System.Collections.Generic.List<long> _enemy = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(13, Name=@"enemy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> enemy
    {
      get { return _enemy; }
    }
  
    private int? _sn;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"sn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sn
    {
      get { return _sn?? default(int); }
      set { _sn = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool snSpecified
    {
      get { return this._sn != null; }
      set { if (value == (this._sn== null)) this._sn = value ? this.sn : (int?)null; }
    }
    private bool ShouldSerializesn() { return snSpecified; }
    private void Resetsn() { snSpecified = false; }
    
    private int? _buy_times;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"buy_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int buy_times
    {
      get { return _buy_times?? default(int); }
      set { _buy_times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool buy_timesSpecified
    {
      get { return this._buy_times != null; }
      set { if (value == (this._buy_times== null)) this._buy_times = value ? this.buy_times : (int?)null; }
    }
    private bool ShouldSerializebuy_times() { return buy_timesSpecified; }
    private void Resetbuy_times() { buy_timesSpecified = false; }
    
    private int? _score;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score?? default(int); }
      set { _score = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool scoreSpecified
    {
      get { return this._score != null; }
      set { if (value == (this._score== null)) this._score = value ? this.score : (int?)null; }
    }
    private bool ShouldSerializescore() { return scoreSpecified; }
    private void Resetscore() { scoreSpecified = false; }
    
    private int? _robot_id;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"robot_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int robot_id
    {
      get { return _robot_id?? default(int); }
      set { _robot_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool robot_idSpecified
    {
      get { return this._robot_id != null; }
      set { if (value == (this._robot_id== null)) this._robot_id = value ? this.robot_id : (int?)null; }
    }
    private bool ShouldSerializerobot_id() { return robot_idSpecified; }
    private void Resetrobot_id() { robot_idSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbArenaInfoList")]
  public partial class pbArenaInfoList : global::ProtoBuf.IExtensible
  {
    public pbArenaInfoList() {}
    
    private readonly global::System.Collections.Generic.List<pb_23.pbArenaInfo> _arena_player_list = new global::System.Collections.Generic.List<pb_23.pbArenaInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"arena_player_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_23.pbArenaInfo> arena_player_list
    {
      get { return _arena_player_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbArenaBattleReport")]
  public partial class pbArenaBattleReport : global::ProtoBuf.IExtensible
  {
    public pbArenaBattleReport() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private int? _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type?? default(int); }
      set { _type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return this._type != null; }
      set { if (value == (this._type== null)) this._type = value ? this.type : (int?)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    
    private int? _result;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result?? default(int); }
      set { _result = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool resultSpecified
    {
      get { return this._result != null; }
      set { if (value == (this._result== null)) this._result = value ? this.result : (int?)null; }
    }
    private bool ShouldSerializeresult() { return resultSpecified; }
    private void Resetresult() { resultSpecified = false; }
    
    private int? _timestamp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timestamp
    {
      get { return _timestamp?? default(int); }
      set { _timestamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timestampSpecified
    {
      get { return this._timestamp != null; }
      set { if (value == (this._timestamp== null)) this._timestamp = value ? this.timestamp : (int?)null; }
    }
    private bool ShouldSerializetimestamp() { return timestampSpecified; }
    private void Resettimestamp() { timestampSpecified = false; }
    
    private int? _player_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id?? default(int); }
      set { _player_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool player_idSpecified
    {
      get { return this._player_id != null; }
      set { if (value == (this._player_id== null)) this._player_id = value ? this.player_id : (int?)null; }
    }
    private bool ShouldSerializeplayer_id() { return player_idSpecified; }
    private void Resetplayer_id() { player_idSpecified = false; }
    
    private string _nickname;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickname
    {
      get { return _nickname?? ""; }
      set { _nickname = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nicknameSpecified
    {
      get { return this._nickname != null; }
      set { if (value == (this._nickname== null)) this._nickname = value ? this.nickname : (string)null; }
    }
    private bool ShouldSerializenickname() { return nicknameSpecified; }
    private void Resetnickname() { nicknameSpecified = false; }
    
    private int? _deffender_id;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"deffender_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int deffender_id
    {
      get { return _deffender_id?? default(int); }
      set { _deffender_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool deffender_idSpecified
    {
      get { return this._deffender_id != null; }
      set { if (value == (this._deffender_id== null)) this._deffender_id = value ? this.deffender_id : (int?)null; }
    }
    private bool ShouldSerializedeffender_id() { return deffender_idSpecified; }
    private void Resetdeffender_id() { deffender_idSpecified = false; }
    
    private string _deffender_name;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"deffender_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string deffender_name
    {
      get { return _deffender_name?? ""; }
      set { _deffender_name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool deffender_nameSpecified
    {
      get { return this._deffender_name != null; }
      set { if (value == (this._deffender_name== null)) this._deffender_name = value ? this.deffender_name : (string)null; }
    }
    private bool ShouldSerializedeffender_name() { return deffender_nameSpecified; }
    private void Resetdeffender_name() { deffender_nameSpecified = false; }
    
    private int? _rank_change_type;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"rank_change_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rank_change_type
    {
      get { return _rank_change_type?? default(int); }
      set { _rank_change_type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rank_change_typeSpecified
    {
      get { return this._rank_change_type != null; }
      set { if (value == (this._rank_change_type== null)) this._rank_change_type = value ? this.rank_change_type : (int?)null; }
    }
    private bool ShouldSerializerank_change_type() { return rank_change_typeSpecified; }
    private void Resetrank_change_type() { rank_change_typeSpecified = false; }
    
    private int? _attack_rank;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"attack_rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attack_rank
    {
      get { return _attack_rank?? default(int); }
      set { _attack_rank = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool attack_rankSpecified
    {
      get { return this._attack_rank != null; }
      set { if (value == (this._attack_rank== null)) this._attack_rank = value ? this.attack_rank : (int?)null; }
    }
    private bool ShouldSerializeattack_rank() { return attack_rankSpecified; }
    private void Resetattack_rank() { attack_rankSpecified = false; }
    
    private int? _deffender_rank;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"deffender_rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int deffender_rank
    {
      get { return _deffender_rank?? default(int); }
      set { _deffender_rank = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool deffender_rankSpecified
    {
      get { return this._deffender_rank != null; }
      set { if (value == (this._deffender_rank== null)) this._deffender_rank = value ? this.deffender_rank : (int?)null; }
    }
    private bool ShouldSerializedeffender_rank() { return deffender_rankSpecified; }
    private void Resetdeffender_rank() { deffender_rankSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbArenaBattleReportList")]
  public partial class pbArenaBattleReportList : global::ProtoBuf.IExtensible
  {
    public pbArenaBattleReportList() {}
    
    private readonly global::System.Collections.Generic.List<pb_23.pbArenaBattleReport> _report_list = new global::System.Collections.Generic.List<pb_23.pbArenaBattleReport>();
    [global::ProtoBuf.ProtoMember(1, Name=@"report_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_23.pbArenaBattleReport> report_list
    {
      get { return _report_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbArenaChallenge")]
  public partial class pbArenaChallenge : global::ProtoBuf.IExtensible
  {
    public pbArenaChallenge() {}
    
    private long? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long id
    {
      get { return _id?? default(long); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (long?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private int? _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result?? default(int); }
      set { _result = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool resultSpecified
    {
      get { return this._result != null; }
      set { if (value == (this._result== null)) this._result = value ? this.result : (int?)null; }
    }
    private bool ShouldSerializeresult() { return resultSpecified; }
    private void Resetresult() { resultSpecified = false; }
    
    private int? _robot;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"robot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int robot
    {
      get { return _robot?? default(int); }
      set { _robot = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool robotSpecified
    {
      get { return this._robot != null; }
      set { if (value == (this._robot== null)) this._robot = value ? this.robot : (int?)null; }
    }
    private bool ShouldSerializerobot() { return robotSpecified; }
    private void Resetrobot() { robotSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbCrossHistory")]
  public partial class pbCrossHistory : global::ProtoBuf.IExtensible
  {
    public pbCrossHistory() {}
    
    private int? _rank;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rank
    {
      get { return _rank?? default(int); }
      set { _rank = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rankSpecified
    {
      get { return this._rank != null; }
      set { if (value == (this._rank== null)) this._rank = value ? this.rank : (int?)null; }
    }
    private bool ShouldSerializerank() { return rankSpecified; }
    private void Resetrank() { rankSpecified = false; }
    
    private int? _round;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"round", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int round
    {
      get { return _round?? default(int); }
      set { _round = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool roundSpecified
    {
      get { return this._round != null; }
      set { if (value == (this._round== null)) this._round = value ? this.round : (int?)null; }
    }
    private bool ShouldSerializeround() { return roundSpecified; }
    private void Resetround() { roundSpecified = false; }
    
    private int? _timestamp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timestamp
    {
      get { return _timestamp?? default(int); }
      set { _timestamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timestampSpecified
    {
      get { return this._timestamp != null; }
      set { if (value == (this._timestamp== null)) this._timestamp = value ? this.timestamp : (int?)null; }
    }
    private bool ShouldSerializetimestamp() { return timestampSpecified; }
    private void Resettimestamp() { timestampSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbCrossHistoryList")]
  public partial class pbCrossHistoryList : global::ProtoBuf.IExtensible
  {
    public pbCrossHistoryList() {}
    
    private readonly global::System.Collections.Generic.List<pb_23.pbCrossHistory> _list = new global::System.Collections.Generic.List<pb_23.pbCrossHistory>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_23.pbCrossHistory> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbCrossIsland")]
  public partial class pbCrossIsland : global::ProtoBuf.IExtensible
  {
    public pbCrossIsland() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private long? _occupy_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"occupy_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long occupy_id
    {
      get { return _occupy_id?? default(long); }
      set { _occupy_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool occupy_idSpecified
    {
      get { return this._occupy_id != null; }
      set { if (value == (this._occupy_id== null)) this._occupy_id = value ? this.occupy_id : (long?)null; }
    }
    private bool ShouldSerializeoccupy_id() { return occupy_idSpecified; }
    private void Resetoccupy_id() { occupy_idSpecified = false; }
    
    private string _occupy_name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"occupy_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string occupy_name
    {
      get { return _occupy_name?? ""; }
      set { _occupy_name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool occupy_nameSpecified
    {
      get { return this._occupy_name != null; }
      set { if (value == (this._occupy_name== null)) this._occupy_name = value ? this.occupy_name : (string)null; }
    }
    private bool ShouldSerializeoccupy_name() { return occupy_nameSpecified; }
    private void Resetoccupy_name() { occupy_nameSpecified = false; }
    
    private int? _occupy_career;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"occupy_career", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int occupy_career
    {
      get { return _occupy_career?? default(int); }
      set { _occupy_career = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool occupy_careerSpecified
    {
      get { return this._occupy_career != null; }
      set { if (value == (this._occupy_career== null)) this._occupy_career = value ? this.occupy_career : (int?)null; }
    }
    private bool ShouldSerializeoccupy_career() { return occupy_careerSpecified; }
    private void Resetoccupy_career() { occupy_careerSpecified = false; }
    
    private int? _occupy_lv;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"occupy_lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int occupy_lv
    {
      get { return _occupy_lv?? default(int); }
      set { _occupy_lv = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool occupy_lvSpecified
    {
      get { return this._occupy_lv != null; }
      set { if (value == (this._occupy_lv== null)) this._occupy_lv = value ? this.occupy_lv : (int?)null; }
    }
    private bool ShouldSerializeoccupy_lv() { return occupy_lvSpecified; }
    private void Resetoccupy_lv() { occupy_lvSpecified = false; }
    
    private int? _occupy_sn;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"occupy_sn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int occupy_sn
    {
      get { return _occupy_sn?? default(int); }
      set { _occupy_sn = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool occupy_snSpecified
    {
      get { return this._occupy_sn != null; }
      set { if (value == (this._occupy_sn== null)) this._occupy_sn = value ? this.occupy_sn : (int?)null; }
    }
    private bool ShouldSerializeoccupy_sn() { return occupy_snSpecified; }
    private void Resetoccupy_sn() { occupy_snSpecified = false; }
    
    private int? _occupy_ability;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"occupy_ability", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int occupy_ability
    {
      get { return _occupy_ability?? default(int); }
      set { _occupy_ability = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool occupy_abilitySpecified
    {
      get { return this._occupy_ability != null; }
      set { if (value == (this._occupy_ability== null)) this._occupy_ability = value ? this.occupy_ability : (int?)null; }
    }
    private bool ShouldSerializeoccupy_ability() { return occupy_abilitySpecified; }
    private void Resetoccupy_ability() { occupy_abilitySpecified = false; }
    
    private int? _occupy_robot;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"occupy_robot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int occupy_robot
    {
      get { return _occupy_robot?? default(int); }
      set { _occupy_robot = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool occupy_robotSpecified
    {
      get { return this._occupy_robot != null; }
      set { if (value == (this._occupy_robot== null)) this._occupy_robot = value ? this.occupy_robot : (int?)null; }
    }
    private bool ShouldSerializeoccupy_robot() { return occupy_robotSpecified; }
    private void Resetoccupy_robot() { occupy_robotSpecified = false; }
    
    private int? _occupy_time;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"occupy_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int occupy_time
    {
      get { return _occupy_time?? default(int); }
      set { _occupy_time = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool occupy_timeSpecified
    {
      get { return this._occupy_time != null; }
      set { if (value == (this._occupy_time== null)) this._occupy_time = value ? this.occupy_time : (int?)null; }
    }
    private bool ShouldSerializeoccupy_time() { return occupy_timeSpecified; }
    private void Resetoccupy_time() { occupy_timeSpecified = false; }
    
    private int? _calc_timestamp;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"calc_timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int calc_timestamp
    {
      get { return _calc_timestamp?? default(int); }
      set { _calc_timestamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool calc_timestampSpecified
    {
      get { return this._calc_timestamp != null; }
      set { if (value == (this._calc_timestamp== null)) this._calc_timestamp = value ? this.calc_timestamp : (int?)null; }
    }
    private bool ShouldSerializecalc_timestamp() { return calc_timestampSpecified; }
    private void Resetcalc_timestamp() { calc_timestampSpecified = false; }
    
    private int? _is_enemy;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"is_enemy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int is_enemy
    {
      get { return _is_enemy?? default(int); }
      set { _is_enemy = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool is_enemySpecified
    {
      get { return this._is_enemy != null; }
      set { if (value == (this._is_enemy== null)) this._is_enemy = value ? this.is_enemy : (int?)null; }
    }
    private bool ShouldSerializeis_enemy() { return is_enemySpecified; }
    private void Resetis_enemy() { is_enemySpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbCrossRecord")]
  public partial class pbCrossRecord : global::ProtoBuf.IExtensible
  {
    public pbCrossRecord() {}
    
    private int? _timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timestamp
    {
      get { return _timestamp?? default(int); }
      set { _timestamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timestampSpecified
    {
      get { return this._timestamp != null; }
      set { if (value == (this._timestamp== null)) this._timestamp = value ? this.timestamp : (int?)null; }
    }
    private bool ShouldSerializetimestamp() { return timestampSpecified; }
    private void Resettimestamp() { timestampSpecified = false; }
    
    private long? _atk_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"atk_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long atk_id
    {
      get { return _atk_id?? default(long); }
      set { _atk_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool atk_idSpecified
    {
      get { return this._atk_id != null; }
      set { if (value == (this._atk_id== null)) this._atk_id = value ? this.atk_id : (long?)null; }
    }
    private bool ShouldSerializeatk_id() { return atk_idSpecified; }
    private void Resetatk_id() { atk_idSpecified = false; }
    
    private string _atk_name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"atk_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string atk_name
    {
      get { return _atk_name?? ""; }
      set { _atk_name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool atk_nameSpecified
    {
      get { return this._atk_name != null; }
      set { if (value == (this._atk_name== null)) this._atk_name = value ? this.atk_name : (string)null; }
    }
    private bool ShouldSerializeatk_name() { return atk_nameSpecified; }
    private void Resetatk_name() { atk_nameSpecified = false; }
    
    private long? _def_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"def_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long def_id
    {
      get { return _def_id?? default(long); }
      set { _def_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool def_idSpecified
    {
      get { return this._def_id != null; }
      set { if (value == (this._def_id== null)) this._def_id = value ? this.def_id : (long?)null; }
    }
    private bool ShouldSerializedef_id() { return def_idSpecified; }
    private void Resetdef_id() { def_idSpecified = false; }
    
    private string _def_name;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"def_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string def_name
    {
      get { return _def_name?? ""; }
      set { _def_name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool def_nameSpecified
    {
      get { return this._def_name != null; }
      set { if (value == (this._def_name== null)) this._def_name = value ? this.def_name : (string)null; }
    }
    private bool ShouldSerializedef_name() { return def_nameSpecified; }
    private void Resetdef_name() { def_nameSpecified = false; }
    
    private int? _result;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result?? default(int); }
      set { _result = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool resultSpecified
    {
      get { return this._result != null; }
      set { if (value == (this._result== null)) this._result = value ? this.result : (int?)null; }
    }
    private bool ShouldSerializeresult() { return resultSpecified; }
    private void Resetresult() { resultSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbCrossFighter")]
  public partial class pbCrossFighter : global::ProtoBuf.IExtensible
  {
    public pbCrossFighter() {}
    
    private int? _times;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int times
    {
      get { return _times?? default(int); }
      set { _times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timesSpecified
    {
      get { return this._times != null; }
      set { if (value == (this._times== null)) this._times = value ? this.times : (int?)null; }
    }
    private bool ShouldSerializetimes() { return timesSpecified; }
    private void Resettimes() { timesSpecified = false; }
    
    private int? _buy_times;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"buy_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int buy_times
    {
      get { return _buy_times?? default(int); }
      set { _buy_times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool buy_timesSpecified
    {
      get { return this._buy_times != null; }
      set { if (value == (this._buy_times== null)) this._buy_times = value ? this.buy_times : (int?)null; }
    }
    private bool ShouldSerializebuy_times() { return buy_timesSpecified; }
    private void Resetbuy_times() { buy_timesSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<pb_23.pbCrossIsland> _islands = new global::System.Collections.Generic.List<pb_23.pbCrossIsland>();
    [global::ProtoBuf.ProtoMember(3, Name=@"islands", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_23.pbCrossIsland> islands
    {
      get { return _islands; }
    }
  
    private readonly global::System.Collections.Generic.List<pb_23.pbCrossRecord> _records = new global::System.Collections.Generic.List<pb_23.pbCrossRecord>();
    [global::ProtoBuf.ProtoMember(4, Name=@"records", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_23.pbCrossRecord> records
    {
      get { return _records; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}