//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: pb_32.proto
namespace pb_32
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbPlayerAchieve")]
  public partial class pbPlayerAchieve : global::ProtoBuf.IExtensible
  {
    public pbPlayerAchieve() {}
    
    private long? _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long player_id
    {
      get { return _player_id?? default(long); }
      set { _player_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool player_idSpecified
    {
      get { return this._player_id != null; }
      set { if (value == (this._player_id== null)) this._player_id = value ? this.player_id : (long?)null; }
    }
    private bool ShouldSerializeplayer_id() { return player_idSpecified; }
    private void Resetplayer_id() { player_idSpecified = false; }
    
    private int? _achieve_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"achieve_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int achieve_id
    {
      get { return _achieve_id?? default(int); }
      set { _achieve_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool achieve_idSpecified
    {
      get { return this._achieve_id != null; }
      set { if (value == (this._achieve_id== null)) this._achieve_id = value ? this.achieve_id : (int?)null; }
    }
    private bool ShouldSerializeachieve_id() { return achieve_idSpecified; }
    private void Resetachieve_id() { achieve_idSpecified = false; }
    
    private int? _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type?? default(int); }
      set { _type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return this._type != null; }
      set { if (value == (this._type== null)) this._type = value ? this.type : (int?)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    
    private int? _finish_flag;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"finish_flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int finish_flag
    {
      get { return _finish_flag?? default(int); }
      set { _finish_flag = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool finish_flagSpecified
    {
      get { return this._finish_flag != null; }
      set { if (value == (this._finish_flag== null)) this._finish_flag = value ? this.finish_flag : (int?)null; }
    }
    private bool ShouldSerializefinish_flag() { return finish_flagSpecified; }
    private void Resetfinish_flag() { finish_flagSpecified = false; }
    
    private int? _goods_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"goods_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int goods_id
    {
      get { return _goods_id?? default(int); }
      set { _goods_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool goods_idSpecified
    {
      get { return this._goods_id != null; }
      set { if (value == (this._goods_id== null)) this._goods_id = value ? this.goods_id : (int?)null; }
    }
    private bool ShouldSerializegoods_id() { return goods_idSpecified; }
    private void Resetgoods_id() { goods_idSpecified = false; }
    
    private int? _num;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num?? default(int); }
      set { _num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numSpecified
    {
      get { return this._num != null; }
      set { if (value == (this._num== null)) this._num = value ? this.num : (int?)null; }
    }
    private bool ShouldSerializenum() { return numSpecified; }
    private void Resetnum() { numSpecified = false; }
    
    private int? _task_id;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"task_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int task_id
    {
      get { return _task_id?? default(int); }
      set { _task_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool task_idSpecified
    {
      get { return this._task_id != null; }
      set { if (value == (this._task_id== null)) this._task_id = value ? this.task_id : (int?)null; }
    }
    private bool ShouldSerializetask_id() { return task_idSpecified; }
    private void Resettask_id() { task_idSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbPlayerAchieveList")]
  public partial class pbPlayerAchieveList : global::ProtoBuf.IExtensible
  {
    public pbPlayerAchieveList() {}
    
    private readonly global::System.Collections.Generic.List<pb_32.pbPlayerAchieve> _pa_list = new global::System.Collections.Generic.List<pb_32.pbPlayerAchieve>();
    [global::ProtoBuf.ProtoMember(1, Name=@"pa_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_32.pbPlayerAchieve> pa_list
    {
      get { return _pa_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}