//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: pb_44.proto
// Note: requires additional types generated from: pb_common.proto
namespace pb_44
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbCampPos")]
  public partial class pbCampPos : global::ProtoBuf.IExtensible
  {
    public pbCampPos() {}
    
    private int? _pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos?? default(int); }
      set { _pos = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool posSpecified
    {
      get { return this._pos != null; }
      set { if (value == (this._pos== null)) this._pos = value ? this.pos : (int?)null; }
    }
    private bool ShouldSerializepos() { return posSpecified; }
    private void Resetpos() { posSpecified = false; }
    
    private long? _goods_uid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"goods_uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long goods_uid
    {
      get { return _goods_uid?? default(long); }
      set { _goods_uid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool goods_uidSpecified
    {
      get { return this._goods_uid != null; }
      set { if (value == (this._goods_uid== null)) this._goods_uid = value ? this.goods_uid : (long?)null; }
    }
    private bool ShouldSerializegoods_uid() { return goods_uidSpecified; }
    private void Resetgoods_uid() { goods_uidSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbCamp")]
  public partial class pbCamp : global::ProtoBuf.IExtensible
  {
    public pbCamp() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<pb_44.pbCampPos> _pos_list = new global::System.Collections.Generic.List<pb_44.pbCampPos>();
    [global::ProtoBuf.ProtoMember(2, Name=@"pos_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_44.pbCampPos> pos_list
    {
      get { return _pos_list; }
    }
  
    private int? _update_timestamp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"update_timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int update_timestamp
    {
      get { return _update_timestamp?? default(int); }
      set { _update_timestamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool update_timestampSpecified
    {
      get { return this._update_timestamp != null; }
      set { if (value == (this._update_timestamp== null)) this._update_timestamp = value ? this.update_timestamp : (int?)null; }
    }
    private bool ShouldSerializeupdate_timestamp() { return update_timestampSpecified; }
    private void Resetupdate_timestamp() { update_timestampSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbPlayerCamp")]
  public partial class pbPlayerCamp : global::ProtoBuf.IExtensible
  {
    public pbPlayerCamp() {}
    
    private long? _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long player_id
    {
      get { return _player_id?? default(long); }
      set { _player_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool player_idSpecified
    {
      get { return this._player_id != null; }
      set { if (value == (this._player_id== null)) this._player_id = value ? this.player_id : (long?)null; }
    }
    private bool ShouldSerializeplayer_id() { return player_idSpecified; }
    private void Resetplayer_id() { player_idSpecified = false; }
    
    private int? _using_camp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"using_camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int using_camp
    {
      get { return _using_camp?? default(int); }
      set { _using_camp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool using_campSpecified
    {
      get { return this._using_camp != null; }
      set { if (value == (this._using_camp== null)) this._using_camp = value ? this.using_camp : (int?)null; }
    }
    private bool ShouldSerializeusing_camp() { return using_campSpecified; }
    private void Resetusing_camp() { using_campSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<pb_44.pbCamp> _camp_list = new global::System.Collections.Generic.List<pb_44.pbCamp>();
    [global::ProtoBuf.ProtoMember(3, Name=@"camp_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_44.pbCamp> camp_list
    {
      get { return _camp_list; }
    }
  
    private int? _update_timestamp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"update_timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int update_timestamp
    {
      get { return _update_timestamp?? default(int); }
      set { _update_timestamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool update_timestampSpecified
    {
      get { return this._update_timestamp != null; }
      set { if (value == (this._update_timestamp== null)) this._update_timestamp = value ? this.update_timestamp : (int?)null; }
    }
    private bool ShouldSerializeupdate_timestamp() { return update_timestampSpecified; }
    private void Resetupdate_timestamp() { update_timestampSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}