//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: pb_9.proto
// Note: requires additional types generated from: pb_common.proto
namespace pb_9
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbnull")]
  public partial class pbnull : global::ProtoBuf.IExtensible
  {
    public pbnull() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbError")]
  public partial class pbError : global::ProtoBuf.IExtensible
  {
    public pbError() {}
    
    private int? _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code?? default(int); }
      set { _error_code = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool error_codeSpecified
    {
      get { return this._error_code != null; }
      set { if (value == (this._error_code== null)) this._error_code = value ? this.error_code : (int?)null; }
    }
    private bool ShouldSerializeerror_code() { return error_codeSpecified; }
    private void Reseterror_code() { error_codeSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<string> _args = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"args", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> args
    {
      get { return _args; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbNewItemInfo")]
  public partial class pbNewItemInfo : global::ProtoBuf.IExtensible
  {
    public pbNewItemInfo() {}
    
    private int? _base_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"base_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int base_id
    {
      get { return _base_id?? default(int); }
      set { _base_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool base_idSpecified
    {
      get { return this._base_id != null; }
      set { if (value == (this._base_id== null)) this._base_id = value ? this.base_id : (int?)null; }
    }
    private bool ShouldSerializebase_id() { return base_idSpecified; }
    private void Resetbase_id() { base_idSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}