//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: pb_common.proto
namespace pb_common
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbResult")]
  public partial class pbResult : global::ProtoBuf.IExtensible
  {
    public pbResult() {}
    
    private int? _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result?? default(int); }
      set { _result = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool resultSpecified
    {
      get { return this._result != null; }
      set { if (value == (this._result== null)) this._result = value ? this.result : (int?)null; }
    }
    private bool ShouldSerializeresult() { return resultSpecified; }
    private void Resetresult() { resultSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbId32")]
  public partial class pbId32 : global::ProtoBuf.IExtensible
  {
    public pbId32() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbId32R")]
  public partial class pbId32R : global::ProtoBuf.IExtensible
  {
    public pbId32R() {}
    
    private readonly global::System.Collections.Generic.List<int> _id = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> id
    {
      get { return _id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbId64")]
  public partial class pbId64 : global::ProtoBuf.IExtensible
  {
    public pbId64() {}
    
    private long? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long id
    {
      get { return _id?? default(long); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (long?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbId64R")]
  public partial class pbId64R : global::ProtoBuf.IExtensible
  {
    public pbId64R() {}
    
    private readonly global::System.Collections.Generic.List<long> _ids = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> ids
    {
      get { return _ids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbIdString")]
  public partial class pbIdString : global::ProtoBuf.IExtensible
  {
    public pbIdString() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id?? ""; }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (string)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbRewardItem")]
  public partial class pbRewardItem : global::ProtoBuf.IExtensible
  {
    public pbRewardItem() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private int? _num;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num?? default(int); }
      set { _num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numSpecified
    {
      get { return this._num != null; }
      set { if (value == (this._num== null)) this._num = value ? this.num : (int?)null; }
    }
    private bool ShouldSerializenum() { return numSpecified; }
    private void Resetnum() { numSpecified = false; }
    
    private int? _goods_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"goods_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int goods_id
    {
      get { return _goods_id?? default(int); }
      set { _goods_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool goods_idSpecified
    {
      get { return this._goods_id != null; }
      set { if (value == (this._goods_id== null)) this._goods_id = value ? this.goods_id : (int?)null; }
    }
    private bool ShouldSerializegoods_id() { return goods_idSpecified; }
    private void Resetgoods_id() { goods_idSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbCombatReward")]
  public partial class pbCombatReward : global::ProtoBuf.IExtensible
  {
    public pbCombatReward() {}
    
    private int? _exp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exp
    {
      get { return _exp?? default(int); }
      set { _exp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool expSpecified
    {
      get { return this._exp != null; }
      set { if (value == (this._exp== null)) this._exp = value ? this.exp : (int?)null; }
    }
    private bool ShouldSerializeexp() { return expSpecified; }
    private void Resetexp() { expSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<pb_common.pbRewardItem> _mon_drop_list = new global::System.Collections.Generic.List<pb_common.pbRewardItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"mon_drop_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_common.pbRewardItem> mon_drop_list
    {
      get { return _mon_drop_list; }
    }
  
    private readonly global::System.Collections.Generic.List<pb_common.pbRewardItem> _dungeon_reward_list = new global::System.Collections.Generic.List<pb_common.pbRewardItem>();
    [global::ProtoBuf.ProtoMember(3, Name=@"dungeon_reward_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_common.pbRewardItem> dungeon_reward_list
    {
      get { return _dungeon_reward_list; }
    }
  
    private long? _unique_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"unique_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long unique_id
    {
      get { return _unique_id?? default(long); }
      set { _unique_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool unique_idSpecified
    {
      get { return this._unique_id != null; }
      set { if (value == (this._unique_id== null)) this._unique_id = value ? this.unique_id : (long?)null; }
    }
    private bool ShouldSerializeunique_id() { return unique_idSpecified; }
    private void Resetunique_id() { unique_idSpecified = false; }
    
    private int? _seal;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"seal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seal
    {
      get { return _seal?? default(int); }
      set { _seal = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sealSpecified
    {
      get { return this._seal != null; }
      set { if (value == (this._seal== null)) this._seal = value ? this.seal : (int?)null; }
    }
    private bool ShouldSerializeseal() { return sealSpecified; }
    private void Resetseal() { sealSpecified = false; }
    
    private int? _evaluate;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"evaluate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int evaluate
    {
      get { return _evaluate?? default(int); }
      set { _evaluate = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool evaluateSpecified
    {
      get { return this._evaluate != null; }
      set { if (value == (this._evaluate== null)) this._evaluate = value ? this.evaluate : (int?)null; }
    }
    private bool ShouldSerializeevaluate() { return evaluateSpecified; }
    private void Resetevaluate() { evaluateSpecified = false; }
    
    private int? _point;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int point
    {
      get { return _point?? default(int); }
      set { _point = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool pointSpecified
    {
      get { return this._point != null; }
      set { if (value == (this._point== null)) this._point = value ? this.point : (int?)null; }
    }
    private bool ShouldSerializepoint() { return pointSpecified; }
    private void Resetpoint() { pointSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<long> _partners = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(8, Name=@"partners", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> partners
    {
      get { return _partners; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbGoodsInfo")]
  public partial class pbGoodsInfo : global::ProtoBuf.IExtensible
  {
    public pbGoodsInfo() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private int? _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num?? default(int); }
      set { _num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numSpecified
    {
      get { return this._num != null; }
      set { if (value == (this._num== null)) this._num = value ? this.num : (int?)null; }
    }
    private bool ShouldSerializenum() { return numSpecified; }
    private void Resetnum() { numSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbGoods")]
  public partial class pbGoods : global::ProtoBuf.IExtensible
  {
    public pbGoods() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private int? _goods_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"goods_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int goods_id
    {
      get { return _goods_id?? default(int); }
      set { _goods_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool goods_idSpecified
    {
      get { return this._goods_id != null; }
      set { if (value == (this._goods_id== null)) this._goods_id = value ? this.goods_id : (int?)null; }
    }
    private bool ShouldSerializegoods_id() { return goods_idSpecified; }
    private void Resetgoods_id() { goods_idSpecified = false; }
    
    private int? _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type?? default(int); }
      set { _type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return this._type != null; }
      set { if (value == (this._type== null)) this._type = value ? this.type : (int?)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    
    private int? _sub_type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sub_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sub_type
    {
      get { return _sub_type?? default(int); }
      set { _sub_type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sub_typeSpecified
    {
      get { return this._sub_type != null; }
      set { if (value == (this._sub_type== null)) this._sub_type = value ? this.sub_type : (int?)null; }
    }
    private bool ShouldSerializesub_type() { return sub_typeSpecified; }
    private void Resetsub_type() { sub_typeSpecified = false; }
    
    private long? _player_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long player_id
    {
      get { return _player_id?? default(long); }
      set { _player_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool player_idSpecified
    {
      get { return this._player_id != null; }
      set { if (value == (this._player_id== null)) this._player_id = value ? this.player_id : (long?)null; }
    }
    private bool ShouldSerializeplayer_id() { return player_idSpecified; }
    private void Resetplayer_id() { player_idSpecified = false; }
    
    private int? _container;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"container", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int container
    {
      get { return _container?? default(int); }
      set { _container = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool containerSpecified
    {
      get { return this._container != null; }
      set { if (value == (this._container== null)) this._container = value ? this.container : (int?)null; }
    }
    private bool ShouldSerializecontainer() { return containerSpecified; }
    private void Resetcontainer() { containerSpecified = false; }
    
    private int? _position;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int position
    {
      get { return _position?? default(int); }
      set { _position = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool positionSpecified
    {
      get { return this._position != null; }
      set { if (value == (this._position== null)) this._position = value ? this.position : (int?)null; }
    }
    private bool ShouldSerializeposition() { return positionSpecified; }
    private void Resetposition() { positionSpecified = false; }
    
    private int? _str_lv;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"str_lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int str_lv
    {
      get { return _str_lv?? default(int); }
      set { _str_lv = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool str_lvSpecified
    {
      get { return this._str_lv != null; }
      set { if (value == (this._str_lv== null)) this._str_lv = value ? this.str_lv : (int?)null; }
    }
    private bool ShouldSerializestr_lv() { return str_lvSpecified; }
    private void Resetstr_lv() { str_lvSpecified = false; }
    
    private int? _star_lv;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"star_lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int star_lv
    {
      get { return _star_lv?? default(int); }
      set { _star_lv = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool star_lvSpecified
    {
      get { return this._star_lv != null; }
      set { if (value == (this._star_lv== null)) this._star_lv = value ? this.star_lv : (int?)null; }
    }
    private bool ShouldSerializestar_lv() { return star_lvSpecified; }
    private void Resetstar_lv() { star_lvSpecified = false; }
    
    private int? _hp_lim;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"hp_lim", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp_lim
    {
      get { return _hp_lim?? default(int); }
      set { _hp_lim = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool hp_limSpecified
    {
      get { return this._hp_lim != null; }
      set { if (value == (this._hp_lim== null)) this._hp_lim = value ? this.hp_lim : (int?)null; }
    }
    private bool ShouldSerializehp_lim() { return hp_limSpecified; }
    private void Resethp_lim() { hp_limSpecified = false; }
    
    private int? _bind;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"bind", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bind
    {
      get { return _bind?? default(int); }
      set { _bind = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool bindSpecified
    {
      get { return this._bind != null; }
      set { if (value == (this._bind== null)) this._bind = value ? this.bind : (int?)null; }
    }
    private bool ShouldSerializebind() { return bindSpecified; }
    private void Resetbind() { bindSpecified = false; }
    
    private int? _attack;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"attack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attack
    {
      get { return _attack?? default(int); }
      set { _attack = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool attackSpecified
    {
      get { return this._attack != null; }
      set { if (value == (this._attack== null)) this._attack = value ? this.attack : (int?)null; }
    }
    private bool ShouldSerializeattack() { return attackSpecified; }
    private void Resetattack() { attackSpecified = false; }
    
    private int? _def;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"def", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int def
    {
      get { return _def?? default(int); }
      set { _def = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool defSpecified
    {
      get { return this._def != null; }
      set { if (value == (this._def== null)) this._def = value ? this.def : (int?)null; }
    }
    private bool ShouldSerializedef() { return defSpecified; }
    private void Resetdef() { defSpecified = false; }
    
    private int? _hit;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"hit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hit
    {
      get { return _hit?? default(int); }
      set { _hit = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool hitSpecified
    {
      get { return this._hit != null; }
      set { if (value == (this._hit== null)) this._hit = value ? this.hit : (int?)null; }
    }
    private bool ShouldSerializehit() { return hitSpecified; }
    private void Resethit() { hitSpecified = false; }
    
    private int? _dodge;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"dodge", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dodge
    {
      get { return _dodge?? default(int); }
      set { _dodge = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dodgeSpecified
    {
      get { return this._dodge != null; }
      set { if (value == (this._dodge== null)) this._dodge = value ? this.dodge : (int?)null; }
    }
    private bool ShouldSerializedodge() { return dodgeSpecified; }
    private void Resetdodge() { dodgeSpecified = false; }
    
    private int? _crit;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"crit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int crit
    {
      get { return _crit?? default(int); }
      set { _crit = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool critSpecified
    {
      get { return this._crit != null; }
      set { if (value == (this._crit== null)) this._crit = value ? this.crit : (int?)null; }
    }
    private bool ShouldSerializecrit() { return critSpecified; }
    private void Resetcrit() { critSpecified = false; }
    
    private int? _anti_crit;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"anti_crit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int anti_crit
    {
      get { return _anti_crit?? default(int); }
      set { _anti_crit = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool anti_critSpecified
    {
      get { return this._anti_crit != null; }
      set { if (value == (this._anti_crit== null)) this._anti_crit = value ? this.anti_crit : (int?)null; }
    }
    private bool ShouldSerializeanti_crit() { return anti_critSpecified; }
    private void Resetanti_crit() { anti_critSpecified = false; }
    
    private int? _stiff;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"stiff", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stiff
    {
      get { return _stiff?? default(int); }
      set { _stiff = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool stiffSpecified
    {
      get { return this._stiff != null; }
      set { if (value == (this._stiff== null)) this._stiff = value ? this.stiff : (int?)null; }
    }
    private bool ShouldSerializestiff() { return stiffSpecified; }
    private void Resetstiff() { stiffSpecified = false; }
    
    private int? _cost;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"cost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cost
    {
      get { return _cost?? default(int); }
      set { _cost = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool costSpecified
    {
      get { return this._cost != null; }
      set { if (value == (this._cost== null)) this._cost = value ? this.cost : (int?)null; }
    }
    private bool ShouldSerializecost() { return costSpecified; }
    private void Resetcost() { costSpecified = false; }
    
    private int? _anti_stiff;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"anti_stiff", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int anti_stiff
    {
      get { return _anti_stiff?? default(int); }
      set { _anti_stiff = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool anti_stiffSpecified
    {
      get { return this._anti_stiff != null; }
      set { if (value == (this._anti_stiff== null)) this._anti_stiff = value ? this.anti_stiff : (int?)null; }
    }
    private bool ShouldSerializeanti_stiff() { return anti_stiffSpecified; }
    private void Resetanti_stiff() { anti_stiffSpecified = false; }
    
    private int? _attack_speed;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"attack_speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attack_speed
    {
      get { return _attack_speed?? default(int); }
      set { _attack_speed = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool attack_speedSpecified
    {
      get { return this._attack_speed != null; }
      set { if (value == (this._attack_speed== null)) this._attack_speed = value ? this.attack_speed : (int?)null; }
    }
    private bool ShouldSerializeattack_speed() { return attack_speedSpecified; }
    private void Resetattack_speed() { attack_speedSpecified = false; }
    
    private int? _move_speed;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"move_speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int move_speed
    {
      get { return _move_speed?? default(int); }
      set { _move_speed = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool move_speedSpecified
    {
      get { return this._move_speed != null; }
      set { if (value == (this._move_speed== null)) this._move_speed = value ? this.move_speed : (int?)null; }
    }
    private bool ShouldSerializemove_speed() { return move_speedSpecified; }
    private void Resetmove_speed() { move_speedSpecified = false; }
    
    private int? _ice;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"ice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ice
    {
      get { return _ice?? default(int); }
      set { _ice = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool iceSpecified
    {
      get { return this._ice != null; }
      set { if (value == (this._ice== null)) this._ice = value ? this.ice : (int?)null; }
    }
    private bool ShouldSerializeice() { return iceSpecified; }
    private void Resetice() { iceSpecified = false; }
    
    private int? _fire;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"fire", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fire
    {
      get { return _fire?? default(int); }
      set { _fire = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool fireSpecified
    {
      get { return this._fire != null; }
      set { if (value == (this._fire== null)) this._fire = value ? this.fire : (int?)null; }
    }
    private bool ShouldSerializefire() { return fireSpecified; }
    private void Resetfire() { fireSpecified = false; }
    
    private int? _honly;
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"honly", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int honly
    {
      get { return _honly?? default(int); }
      set { _honly = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool honlySpecified
    {
      get { return this._honly != null; }
      set { if (value == (this._honly== null)) this._honly = value ? this.honly : (int?)null; }
    }
    private bool ShouldSerializehonly() { return honlySpecified; }
    private void Resethonly() { honlySpecified = false; }
    
    private int? _dark;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"dark", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dark
    {
      get { return _dark?? default(int); }
      set { _dark = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool darkSpecified
    {
      get { return this._dark != null; }
      set { if (value == (this._dark== null)) this._dark = value ? this.dark : (int?)null; }
    }
    private bool ShouldSerializedark() { return darkSpecified; }
    private void Resetdark() { darkSpecified = false; }
    
    private int? _anti_ice;
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"anti_ice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int anti_ice
    {
      get { return _anti_ice?? default(int); }
      set { _anti_ice = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool anti_iceSpecified
    {
      get { return this._anti_ice != null; }
      set { if (value == (this._anti_ice== null)) this._anti_ice = value ? this.anti_ice : (int?)null; }
    }
    private bool ShouldSerializeanti_ice() { return anti_iceSpecified; }
    private void Resetanti_ice() { anti_iceSpecified = false; }
    
    private int? _anti_fire;
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"anti_fire", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int anti_fire
    {
      get { return _anti_fire?? default(int); }
      set { _anti_fire = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool anti_fireSpecified
    {
      get { return this._anti_fire != null; }
      set { if (value == (this._anti_fire== null)) this._anti_fire = value ? this.anti_fire : (int?)null; }
    }
    private bool ShouldSerializeanti_fire() { return anti_fireSpecified; }
    private void Resetanti_fire() { anti_fireSpecified = false; }
    
    private int? _anti_honly;
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"anti_honly", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int anti_honly
    {
      get { return _anti_honly?? default(int); }
      set { _anti_honly = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool anti_honlySpecified
    {
      get { return this._anti_honly != null; }
      set { if (value == (this._anti_honly== null)) this._anti_honly = value ? this.anti_honly : (int?)null; }
    }
    private bool ShouldSerializeanti_honly() { return anti_honlySpecified; }
    private void Resetanti_honly() { anti_honlySpecified = false; }
    
    private int? _anti_dark;
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"anti_dark", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int anti_dark
    {
      get { return _anti_dark?? default(int); }
      set { _anti_dark = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool anti_darkSpecified
    {
      get { return this._anti_dark != null; }
      set { if (value == (this._anti_dark== null)) this._anti_dark = value ? this.anti_dark : (int?)null; }
    }
    private bool ShouldSerializeanti_dark() { return anti_darkSpecified; }
    private void Resetanti_dark() { anti_darkSpecified = false; }
    
    private int? _power;
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int power
    {
      get { return _power?? default(int); }
      set { _power = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool powerSpecified
    {
      get { return this._power != null; }
      set { if (value == (this._power== null)) this._power = value ? this.power : (int?)null; }
    }
    private bool ShouldSerializepower() { return powerSpecified; }
    private void Resetpower() { powerSpecified = false; }
    
    private int? _quality;
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int quality
    {
      get { return _quality?? default(int); }
      set { _quality = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool qualitySpecified
    {
      get { return this._quality != null; }
      set { if (value == (this._quality== null)) this._quality = value ? this.quality : (int?)null; }
    }
    private bool ShouldSerializequality() { return qualitySpecified; }
    private void Resetquality() { qualitySpecified = false; }
    
    private readonly global::System.Collections.Generic.List<int> _jewels = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(33, Name=@"jewels", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> jewels
    {
      get { return _jewels; }
    }
  
    private int? _sum;
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"sum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sum
    {
      get { return _sum?? default(int); }
      set { _sum = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sumSpecified
    {
      get { return this._sum != null; }
      set { if (value == (this._sum== null)) this._sum = value ? this.sum : (int?)null; }
    }
    private bool ShouldSerializesum() { return sumSpecified; }
    private void Resetsum() { sumSpecified = false; }
    
    private int? _hp_lim_ext;
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"hp_lim_ext", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp_lim_ext
    {
      get { return _hp_lim_ext?? default(int); }
      set { _hp_lim_ext = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool hp_lim_extSpecified
    {
      get { return this._hp_lim_ext != null; }
      set { if (value == (this._hp_lim_ext== null)) this._hp_lim_ext = value ? this.hp_lim_ext : (int?)null; }
    }
    private bool ShouldSerializehp_lim_ext() { return hp_lim_extSpecified; }
    private void Resethp_lim_ext() { hp_lim_extSpecified = false; }
    
    private int? _attack_ext;
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"attack_ext", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attack_ext
    {
      get { return _attack_ext?? default(int); }
      set { _attack_ext = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool attack_extSpecified
    {
      get { return this._attack_ext != null; }
      set { if (value == (this._attack_ext== null)) this._attack_ext = value ? this.attack_ext : (int?)null; }
    }
    private bool ShouldSerializeattack_ext() { return attack_extSpecified; }
    private void Resetattack_ext() { attack_extSpecified = false; }
    
    private int? _hit_ext;
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"hit_ext", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hit_ext
    {
      get { return _hit_ext?? default(int); }
      set { _hit_ext = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool hit_extSpecified
    {
      get { return this._hit_ext != null; }
      set { if (value == (this._hit_ext== null)) this._hit_ext = value ? this.hit_ext : (int?)null; }
    }
    private bool ShouldSerializehit_ext() { return hit_extSpecified; }
    private void Resethit_ext() { hit_extSpecified = false; }
    
    private int? _dodge_ext;
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"dodge_ext", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dodge_ext
    {
      get { return _dodge_ext?? default(int); }
      set { _dodge_ext = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dodge_extSpecified
    {
      get { return this._dodge_ext != null; }
      set { if (value == (this._dodge_ext== null)) this._dodge_ext = value ? this.dodge_ext : (int?)null; }
    }
    private bool ShouldSerializedodge_ext() { return dodge_extSpecified; }
    private void Resetdodge_ext() { dodge_extSpecified = false; }
    
    private int? _def_ext;
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"def_ext", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int def_ext
    {
      get { return _def_ext?? default(int); }
      set { _def_ext = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool def_extSpecified
    {
      get { return this._def_ext != null; }
      set { if (value == (this._def_ext== null)) this._def_ext = value ? this.def_ext : (int?)null; }
    }
    private bool ShouldSerializedef_ext() { return def_extSpecified; }
    private void Resetdef_ext() { def_extSpecified = false; }
    
    private int? _crit_ext;
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"crit_ext", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int crit_ext
    {
      get { return _crit_ext?? default(int); }
      set { _crit_ext = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool crit_extSpecified
    {
      get { return this._crit_ext != null; }
      set { if (value == (this._crit_ext== null)) this._crit_ext = value ? this.crit_ext : (int?)null; }
    }
    private bool ShouldSerializecrit_ext() { return crit_extSpecified; }
    private void Resetcrit_ext() { crit_extSpecified = false; }
    
    private int? _anti_crit_ext;
    [global::ProtoBuf.ProtoMember(41, IsRequired = false, Name=@"anti_crit_ext", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int anti_crit_ext
    {
      get { return _anti_crit_ext?? default(int); }
      set { _anti_crit_ext = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool anti_crit_extSpecified
    {
      get { return this._anti_crit_ext != null; }
      set { if (value == (this._anti_crit_ext== null)) this._anti_crit_ext = value ? this.anti_crit_ext : (int?)null; }
    }
    private bool ShouldSerializeanti_crit_ext() { return anti_crit_extSpecified; }
    private void Resetanti_crit_ext() { anti_crit_extSpecified = false; }
    
    private int? _mana_lim;
    [global::ProtoBuf.ProtoMember(42, IsRequired = false, Name=@"mana_lim", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mana_lim
    {
      get { return _mana_lim?? default(int); }
      set { _mana_lim = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool mana_limSpecified
    {
      get { return this._mana_lim != null; }
      set { if (value == (this._mana_lim== null)) this._mana_lim = value ? this.mana_lim : (int?)null; }
    }
    private bool ShouldSerializemana_lim() { return mana_limSpecified; }
    private void Resetmana_lim() { mana_limSpecified = false; }
    
    private int? _mana_rec;
    [global::ProtoBuf.ProtoMember(43, IsRequired = false, Name=@"mana_rec", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mana_rec
    {
      get { return _mana_rec?? default(int); }
      set { _mana_rec = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool mana_recSpecified
    {
      get { return this._mana_rec != null; }
      set { if (value == (this._mana_rec== null)) this._mana_rec = value ? this.mana_rec : (int?)null; }
    }
    private bool ShouldSerializemana_rec() { return mana_recSpecified; }
    private void Resetmana_rec() { mana_recSpecified = false; }
    
    private int? _mana_lim_ext;
    [global::ProtoBuf.ProtoMember(44, IsRequired = false, Name=@"mana_lim_ext", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mana_lim_ext
    {
      get { return _mana_lim_ext?? default(int); }
      set { _mana_lim_ext = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool mana_lim_extSpecified
    {
      get { return this._mana_lim_ext != null; }
      set { if (value == (this._mana_lim_ext== null)) this._mana_lim_ext = value ? this.mana_lim_ext : (int?)null; }
    }
    private bool ShouldSerializemana_lim_ext() { return mana_lim_extSpecified; }
    private void Resetmana_lim_ext() { mana_lim_extSpecified = false; }
    
    private int? _mana_rec_ext;
    [global::ProtoBuf.ProtoMember(45, IsRequired = false, Name=@"mana_rec_ext", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mana_rec_ext
    {
      get { return _mana_rec_ext?? default(int); }
      set { _mana_rec_ext = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool mana_rec_extSpecified
    {
      get { return this._mana_rec_ext != null; }
      set { if (value == (this._mana_rec_ext== null)) this._mana_rec_ext = value ? this.mana_rec_ext : (int?)null; }
    }
    private bool ShouldSerializemana_rec_ext() { return mana_rec_extSpecified; }
    private void Resetmana_rec_ext() { mana_rec_extSpecified = false; }
    
    private int? _skill_card_exp;
    [global::ProtoBuf.ProtoMember(46, IsRequired = false, Name=@"skill_card_exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill_card_exp
    {
      get { return _skill_card_exp?? default(int); }
      set { _skill_card_exp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool skill_card_expSpecified
    {
      get { return this._skill_card_exp != null; }
      set { if (value == (this._skill_card_exp== null)) this._skill_card_exp = value ? this.skill_card_exp : (int?)null; }
    }
    private bool ShouldSerializeskill_card_exp() { return skill_card_expSpecified; }
    private void Resetskill_card_exp() { skill_card_expSpecified = false; }
    
    private int? _card_pos_1;
    [global::ProtoBuf.ProtoMember(47, IsRequired = false, Name=@"card_pos_1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card_pos_1
    {
      get { return _card_pos_1?? default(int); }
      set { _card_pos_1 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool card_pos_1Specified
    {
      get { return this._card_pos_1 != null; }
      set { if (value == (this._card_pos_1== null)) this._card_pos_1 = value ? this.card_pos_1 : (int?)null; }
    }
    private bool ShouldSerializecard_pos_1() { return card_pos_1Specified; }
    private void Resetcard_pos_1() { card_pos_1Specified = false; }
    
    private int? _card_pos_2;
    [global::ProtoBuf.ProtoMember(48, IsRequired = false, Name=@"card_pos_2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card_pos_2
    {
      get { return _card_pos_2?? default(int); }
      set { _card_pos_2 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool card_pos_2Specified
    {
      get { return this._card_pos_2 != null; }
      set { if (value == (this._card_pos_2== null)) this._card_pos_2 = value ? this.card_pos_2 : (int?)null; }
    }
    private bool ShouldSerializecard_pos_2() { return card_pos_2Specified; }
    private void Resetcard_pos_2() { card_pos_2Specified = false; }
    
    private int? _card_pos_3;
    [global::ProtoBuf.ProtoMember(49, IsRequired = false, Name=@"card_pos_3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card_pos_3
    {
      get { return _card_pos_3?? default(int); }
      set { _card_pos_3 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool card_pos_3Specified
    {
      get { return this._card_pos_3 != null; }
      set { if (value == (this._card_pos_3== null)) this._card_pos_3 = value ? this.card_pos_3 : (int?)null; }
    }
    private bool ShouldSerializecard_pos_3() { return card_pos_3Specified; }
    private void Resetcard_pos_3() { card_pos_3Specified = false; }
    
    private readonly global::System.Collections.Generic.List<pb_common.pbGoodsInfo> _value = new global::System.Collections.Generic.List<pb_common.pbGoodsInfo>();
    [global::ProtoBuf.ProtoMember(50, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_common.pbGoodsInfo> value
    {
      get { return _value; }
    }
  
    private int? _timestamp;
    [global::ProtoBuf.ProtoMember(51, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timestamp
    {
      get { return _timestamp?? default(int); }
      set { _timestamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timestampSpecified
    {
      get { return this._timestamp != null; }
      set { if (value == (this._timestamp== null)) this._timestamp = value ? this.timestamp : (int?)null; }
    }
    private bool ShouldSerializetimestamp() { return timestampSpecified; }
    private void Resettimestamp() { timestampSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbSkill")]
  public partial class pbSkill : global::ProtoBuf.IExtensible
  {
    public pbSkill() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private int? _skill_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill_id
    {
      get { return _skill_id?? default(int); }
      set { _skill_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool skill_idSpecified
    {
      get { return this._skill_id != null; }
      set { if (value == (this._skill_id== null)) this._skill_id = value ? this.skill_id : (int?)null; }
    }
    private bool ShouldSerializeskill_id() { return skill_idSpecified; }
    private void Resetskill_id() { skill_idSpecified = false; }
    
    private int? _player_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id?? default(int); }
      set { _player_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool player_idSpecified
    {
      get { return this._player_id != null; }
      set { if (value == (this._player_id== null)) this._player_id = value ? this.player_id : (int?)null; }
    }
    private bool ShouldSerializeplayer_id() { return player_idSpecified; }
    private void Resetplayer_id() { player_idSpecified = false; }
    
    private int? _lv;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lv
    {
      get { return _lv?? default(int); }
      set { _lv = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lvSpecified
    {
      get { return this._lv != null; }
      set { if (value == (this._lv== null)) this._lv = value ? this.lv : (int?)null; }
    }
    private bool ShouldSerializelv() { return lvSpecified; }
    private void Resetlv() { lvSpecified = false; }
    
    private int? _str_lv;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"str_lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int str_lv
    {
      get { return _str_lv?? default(int); }
      set { _str_lv = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool str_lvSpecified
    {
      get { return this._str_lv != null; }
      set { if (value == (this._str_lv== null)) this._str_lv = value ? this.str_lv : (int?)null; }
    }
    private bool ShouldSerializestr_lv() { return str_lvSpecified; }
    private void Resetstr_lv() { str_lvSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<int> _sigil = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"sigil", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> sigil
    {
      get { return _sigil; }
    }
  
    private int? _type;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type?? default(int); }
      set { _type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return this._type != null; }
      set { if (value == (this._type== null)) this._type = value ? this.type : (int?)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pbFriend")]
  public partial class pbFriend : global::ProtoBuf.IExtensible
  {
    public pbFriend() {}
    
    private long? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long id
    {
      get { return _id?? default(long); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (long?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private string _nickname;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickname
    {
      get { return _nickname?? ""; }
      set { _nickname = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nicknameSpecified
    {
      get { return this._nickname != null; }
      set { if (value == (this._nickname== null)) this._nickname = value ? this.nickname : (string)null; }
    }
    private bool ShouldSerializenickname() { return nicknameSpecified; }
    private void Resetnickname() { nicknameSpecified = false; }
    
    private int? _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level?? default(int); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return this._level != null; }
      set { if (value == (this._level== null)) this._level = value ? this.level : (int?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    
    private int? _career;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"career", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int career
    {
      get { return _career?? default(int); }
      set { _career = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool careerSpecified
    {
      get { return this._career != null; }
      set { if (value == (this._career== null)) this._career = value ? this.career : (int?)null; }
    }
    private bool ShouldSerializecareer() { return careerSpecified; }
    private void Resetcareer() { careerSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<pb_common.pbGoods> _core = new global::System.Collections.Generic.List<pb_common.pbGoods>();
    [global::ProtoBuf.ProtoMember(5, Name=@"core", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_common.pbGoods> core
    {
      get { return _core; }
    }
  
    private int? _off_time;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"off_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int off_time
    {
      get { return _off_time?? default(int); }
      set { _off_time = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool off_timeSpecified
    {
      get { return this._off_time != null; }
      set { if (value == (this._off_time== null)) this._off_time = value ? this.off_time : (int?)null; }
    }
    private bool ShouldSerializeoff_time() { return off_timeSpecified; }
    private void Resetoff_time() { off_timeSpecified = false; }
    
    private int? _fashion;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"fashion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fashion
    {
      get { return _fashion?? default(int); }
      set { _fashion = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool fashionSpecified
    {
      get { return this._fashion != null; }
      set { if (value == (this._fashion== null)) this._fashion = value ? this.fashion : (int?)null; }
    }
    private bool ShouldSerializefashion() { return fashionSpecified; }
    private void Resetfashion() { fashionSpecified = false; }
    
    private int? _mugen_pass_times;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"mugen_pass_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mugen_pass_times
    {
      get { return _mugen_pass_times?? default(int); }
      set { _mugen_pass_times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool mugen_pass_timesSpecified
    {
      get { return this._mugen_pass_times != null; }
      set { if (value == (this._mugen_pass_times== null)) this._mugen_pass_times = value ? this.mugen_pass_times : (int?)null; }
    }
    private bool ShouldSerializemugen_pass_times() { return mugen_pass_timesSpecified; }
    private void Resetmugen_pass_times() { mugen_pass_timesSpecified = false; }
    
    private int? _mugen_score;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"mugen_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mugen_score
    {
      get { return _mugen_score?? default(int); }
      set { _mugen_score = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool mugen_scoreSpecified
    {
      get { return this._mugen_score != null; }
      set { if (value == (this._mugen_score== null)) this._mugen_score = value ? this.mugen_score : (int?)null; }
    }
    private bool ShouldSerializemugen_score() { return mugen_scoreSpecified; }
    private void Resetmugen_score() { mugen_scoreSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<pb_common.pbSkill> _skill_list = new global::System.Collections.Generic.List<pb_common.pbSkill>();
    [global::ProtoBuf.ProtoMember(10, Name=@"skill_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_common.pbSkill> skill_list
    {
      get { return _skill_list; }
    }
  
    private readonly global::System.Collections.Generic.List<pb_common.pbSkill> _talent = new global::System.Collections.Generic.List<pb_common.pbSkill>();
    [global::ProtoBuf.ProtoMember(11, Name=@"talent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb_common.pbSkill> talent
    {
      get { return _talent; }
    }
  
    private int? _battle_ability;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"battle_ability", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int battle_ability
    {
      get { return _battle_ability?? default(int); }
      set { _battle_ability = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool battle_abilitySpecified
    {
      get { return this._battle_ability != null; }
      set { if (value == (this._battle_ability== null)) this._battle_ability = value ? this.battle_ability : (int?)null; }
    }
    private bool ShouldSerializebattle_ability() { return battle_abilitySpecified; }
    private void Resetbattle_ability() { battle_abilitySpecified = false; }
    
    private int? _rela;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"rela", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rela
    {
      get { return _rela?? default(int); }
      set { _rela = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool relaSpecified
    {
      get { return this._rela != null; }
      set { if (value == (this._rela== null)) this._rela = value ? this.rela : (int?)null; }
    }
    private bool ShouldSerializerela() { return relaSpecified; }
    private void Resetrela() { relaSpecified = false; }
    
    private string _league_name;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"league_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string league_name
    {
      get { return _league_name?? ""; }
      set { _league_name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool league_nameSpecified
    {
      get { return this._league_name != null; }
      set { if (value == (this._league_name== null)) this._league_name = value ? this.league_name : (string)null; }
    }
    private bool ShouldSerializeleague_name() { return league_nameSpecified; }
    private void Resetleague_name() { league_nameSpecified = false; }
    
    private int? _league_title;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"league_title", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int league_title
    {
      get { return _league_title?? default(int); }
      set { _league_title = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool league_titleSpecified
    {
      get { return this._league_title != null; }
      set { if (value == (this._league_title== null)) this._league_title = value ? this.league_title : (int?)null; }
    }
    private bool ShouldSerializeleague_title() { return league_titleSpecified; }
    private void Resetleague_title() { league_titleSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<int> _put_on_skill = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(16, Name=@"put_on_skill", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> put_on_skill
    {
      get { return _put_on_skill; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}